### ISSUE TITLE
[BUG]: Fix Android namespace Issue

### ISSUE THREAD

**Issue by JHarzenetter** [Canardoux/flutter_sound#1021]
### Flutter Version
Flutter Version 3.19.2

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
```
STDIN
????????? flutter_sound 9.3.8
???   ????????? flutter_sound_platform_interface 9.3.8
???   ????????? flutter_sound_web 9.3.8
???   ???   ????????? flutter_sound_platform_interface...
```

----------------------------------------------------------

## Severity
- Cannot build my App 

--------------------------------------------------------

## Platforms you faced the error 

- Android 

--------------------------------------------------------

# Logs!!!!
```
A problem occurred configuring project ':flutter_sound'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```
See [this](https://tau.canardoux.xyz/logger.html)

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
@JHarzenetter : do you have another Java plugin or flutter sound is the only Java plugin?

**Comment by JHarzenetter** [comment]
Its the only Plugin

**Comment by JHarzenetter** [comment]
The solution to this would be adding the following to the Android block in the build.gradle
```
// Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
      namespace 'xyz.canardoux.fluttersound'
    }
```

**Comment by JHarzenetter** [comment]
Great News. That shouldn't be a problem

**Comment by Larpoux** [comment]
@JHarzenetter :  this is fixed in Flutter Sound  9.4.5

Please, could you check if it is OK now, and close this issue if everything good ?

**Comment by Larpoux** [comment]
OK @JHarzenetter .

Please reopen this issue if not fixed in flutter Sound 9.4.5

**Comment by AlaJaber97** [comment]
still the issue exists
![image](https://github.com/Canardoux/flutter_sound/assets/40597191/be91d1bf-967d-4b44-9ab4-bc9110280757)

**Comment by Larpoux** [comment]
Strange: I thought that this problem was fixed. I am going to look tomorrow if I understand why. Of course are you sure you use >v9.4.5 ?

**Comment by Larpoux** [comment]
Can you check your AGP version (Android Gradle Plugin) ?

**Comment by Larpoux** [comment]
@AlaJaber97 : 
I don't see any problem.

Please check : 
- Your Flutter Sound Version (must be >= 9.4.5)
- Your AGP Version 
- Your Gradle Version (I use 8.6)
- Your SDK tools Version (I use Android API 34 Extension Level 9)

How do you build your App ? You can try to use a recent version of Android Studio because this Program does many things to manage the various versions (mine isAndroid Studio Iguana | 2023.2.1 Patch 2)

**Comment by AlaJaber97** [comment]
You're right, I was using Flutter Sound version 8.5. After upgrading, the issue was resolved.
