### ISSUE TITLE
No sound when playing audio in iOS silent mode

### ISSUE THREAD

**Issue by quentin996007** [Canardoux/flutter_sound#1028]
In iOS, I am using FlutterSoundPlayer for voice playback, I don't hear sound in silent mode, how do I ignore silent mode, I want sound to play no matter what mode I am in. Thanks for the help!

**Comment by gzimbron** [comment]
I come from flutter_sound_lite, which allows me to play sounds even when iPhone is in silent mode. 

Is there a way to activate this mode in flutter_sound?

**Comment by Larpoux** [comment]
Flutter Sound lite was a very long time ago!
At this time, Flutter Sound tried to manage itself the Audio Sessions.
We stopped doing that because several people complained that Flutter Sound was incompatible with others sound lib.

Perhaps you can look to the Flutter Audio Session plugin and see if some parameters can help.

**Comment by Larpoux** [comment]
Please reopen this issue if you have till problems

**Comment by ismail-go** [comment]
Hi, I have same issue in ios. There is no sound while the device is on silent mode. in other packages has respectSilence flag. How do we handle this situation?

**Comment by JayeshMardiya** [comment]
In your `ios/Runner/Info.plist`, add the following permissions:
```<key>UIBackgroundModes</key>
<array>
  <string>audio</string>
</array>
<key>NSMicrophoneUsageDescription</key>
<string>We need microphone access to play audio.</string>
```

Put this code in AppDelegate didFinishLaunchingWithOptions method
```
do {
            try AVAudioSession.sharedInstance().setCategory(
                .playback, mode: .default, options: [])
            try AVAudioSession.sharedInstance().setActive(true)
        } catch { print("Failed to set audio session category.") }
```

- Setting the `AVAudioSession` to `.playback` mode allows the audio to play through the speaker even when the device is in silent mode.
- Using `UIBackgroundModes` ensures audio continues to play in the background.
