### ISSUE TITLE
[HELP]:warner_tautz_off_broadway.mp3

### ISSUE THREAD

**Issue by git-boya** [Canardoux/flutter_sound#1030]
------------

I need Help for :

- Using the API ?

- Generate an iOS or Android App ?

- Debugging my App ?

- Other ?

-------------------------------------
## Here is my question :
There is an warner_tautz_off_broadway.mp3 file in the`flutter_sound_core/android/src/main/res/raw` directory,
that must exist? It is approximately 1M in size, can it be deleted?
![image](https://github.com/Canardoux/flutter_sound/assets/17589102/11ca5db7-9d03-4af1-b9e6-e8cd8595a067)

**Comment by Larpoux** [comment]
Yes, you are right. I will remove this file in the next version of flutter sound

**Comment by git-boya** [comment]
Thank you, it has already taken effect
