### ISSUE TITLE
[BUG]:-[FlutterSoundRecorder startRecorder:result:] com.apple.coreaudio.avfaudio - required condition is false: format.sampleRate == hwFormat.sampleRate

### ISSUE THREAD

**Issue by coder-dongjiayi** [Canardoux/flutter_sound#1034]
## Flutter Sound Version : 

flutter_sound: ^9.4.6

----------------------------------------------------------

## Severity

- Crash 

Fatal Exception: com.apple.coreaudio.avfaudio
required condition is false: format.sampleRate == hwFormat.sampleRate

--------------------------------------------------------

## Platforms you faced the error 

- iOS
------------------------------------------------

**Describe the bug**
firsebase monitored a number of users who were recording while the program crashed.

![20240515152519](https://github.com/Canardoux/flutter_sound/assets/9606416/406c1166-577f-4582-88bb-4a912cee330e)
my code
``` 
    await _record.openRecorder();
    await _initSession();
    await _record.startRecorder(codec: Codec.pcm16, toFile: _recordPcmPath);

```

**Comment by Larpoux** [comment]
Yes @coder-dongjiayi ,

There is something bad with RAW PCM (notably with Streams) on iOS.
I want to rewrite all this bad code, but this is a major work for me, and I don't have much time. So don't expect to have this fixed soon.

In the mean time, perhaps you can record a WAV sound, and translate your file to RAW PCM, ( if you really need RAW PCM ).
WAV is just RAW PCM with an envelop in front of the data so it is very easy to remove this envelop.
You can use flutter_soud/util/flutter_sound_helper : 
```dart
Future<void> waveToPCM({
    required String inputFile,
    required String outputFile,
  }) async {
```

**Comment by coder-dongjiayi** [comment]
okay, I will try using wav。
