### ISSUE TITLE
Play audio from live stream url is not working in iOS but working in android

### ISSUE THREAD

**Issue by sridevi0512** [Canardoux/flutter_sound#1051]
I am getting live stream url from server side and play the audio its working fine in android but not working in iOS

**Comment by Larpoux** [comment]
Please, give us the logs and an extract of your code

**Comment by minhtritc97** [comment]
if url without extension file then it is not working on ios
u can try url: https://mediadev.theadvance.com/chat/d866cb18-fa66-4129-b681-23f74994aa52
