### ISSUE TITLE
[BUG]: 🙌🏻 Please update js ^0.6.2 to js ^0.7.1 

### ISSUE THREAD

**Issue by osmirnova-voc** [Canardoux/flutter_sound#1054]
## Flutter Sound Version : 9.4.6

- **FULL** or **LITE** flavor ?

Because flutter_sound >=9.6.0 depends on flutter_sound_web 9.6.0 which depends on js ^0.6.2, flutter_sound >=9.6.0 requires js ^0.6.2.
And because pushy_flutter 2.0.20 depends on js ^0.7.1 and no versions of pushy_flutter match >2.0.20 <3.0.0, flutter_sound >=9.6.0 is incompatible with pushy_flutter ^2.0.20.

**Comment by Larpoux** [comment]
@osmirnova-voc : Flutter Sound 9.7.0 is released with a dependency to `js: ^0.7.1'.

**Comment by osmirnova-voc** [comment]
Thank u!
