### ISSUE TITLE
[HELP]: startPlayerFromStream not calling whenFinished callback

### ISSUE THREAD

**Issue by rurico** [Canardoux/flutter_sound#1058]
I need Help for :
- Using the API
-------------------------------------
## my question :

I'm trying to use the `startPlayerFromStream` method of FlutterSoundPlayer, but the `whenFinished` callback is not being called after playback completes. Here's my code:

```dart
class Test {
  final FlutterSoundPlayer _mPlayer = FlutterSoundPlayer(logLevel: Level.off);

  Future<void> startPlay(TWhenFinished whenFinished) async {
    await _mPlayer.openPlayer();
    await _mPlayer.startPlayerFromStream(
      codec: Codec.pcm16,
      numChannels: 1,
      sampleRate: 16000,
      whenFinished: whenFinished,
    );
  }

  void addStream(Uint8List stream) {
    _mPlayer.foodSink?.add(FoodData(stream));
  }
}
```

I call `startPlay` to begin playback, then use `addStream` to add data. However, after playback finishes, the `whenFinished` callback is not triggered. 

Could you please advise on how to properly use these methods to ensure the `whenFinished` callback is called? Thank you for your help.

**Comment by Larpoux** [comment]
Recently I did some work to support the `WhenFinished` on stream.
Are you sure to use the last version of flutter sound?
What is your platform? iOS or Android?
Do you loop very quickly on addstream() and then stop feeding your stream?

i am interested by your issue because I am actually working on that.

**Comment by rurico** [comment]
Thank you for your prompt response, @Larpoux. I appreciate your interest in this issue.

To address your questions:

1. Platform: Android
2. Version: flutter_sound: ^9.7.2 (latest)

I'm implementing an OpenAI-like voice interaction feature. As text SSE streams are received, I send them to the server to generate TTS audio streams.

My process:
1. Call `startPlay` before the first word's TTS audio stream is generated.
2. Immediately call `addStream` when audio streams are received.
This part works well :blush:

When the TTS stream ends, I've tried calling `_mPlayer.foodSink?.close()` to end the stream, but `whenFinished` still doesn't trigger.

Is there anything else I should be doing to ensure `whenFinished` is called properly? Your insights would be greatly appreciated.

**Comment by LiquidError** [comment]
@rurico, Did you find a solution yourself? I'm having the same issue: I can't find a way to have the player indicate it finished playing from the stream.

**Comment by LiquidError** [comment]
@rurico Thanks for sharing! I solved it another way, but that seems even better. I'll check it out. Thanks again!
