### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by SharifboyMuminov** [Canardoux/flutter_sound#1059]
## Flutter Sound Version : 

- **FULL** or **LITE** flavor ?

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

## Severity

- Crash ?

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone 14 Pro Max.

I have a new issue, this issue haven't yesterday, my app has ran but now it's not

- Android ?

- Flutter Web ?

- Emulator ? 

- Real device ?

------------------------------------------------

**Describe the bug**

**To Reproduce**
----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug).
To activate the logs, you must instantiate your modules with the Log Level set to `Level.debug` :
```
FlutterSoundPlayer myPlayer = FlutterSoundPlayer(logLevel: Level.debug);
FlutterSoundRecorder myRecorder = FlutterSoundRecorder(logLevel: Level.debug);
```
See [this](https://tau.canardoux.xyz/logger.html)

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
> Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
> To update the CocoaPods specs, run:
> pod repo update

A new Flutter Sound has been released yesterday.
The dependencies are now more recent. Just go to your iOS folder and type `pod repo update`.
If you have difficulties, tell me. I will help you.

**Comment by Larpoux** [comment]
Please, reopen this issue if still problems
