### ISSUE TITLE
[BUG]:record_to_stream_example recordingDataController.stream.listen Not effective

### ISSUE THREAD

**Issue by SheepYang1993** [Canardoux/flutter_sound#1060]
The following code does not take effect in record_to-steream_example
```
    _mRecordingDataSubscription = recordingDataController.stream.listen((buf) {
      //if (buf is FoodData) {
      buffer.addAll(buf!);
      //}
    });
```

**Comment by Larpoux** [comment]
I am actually working on recording to stream.
I am sorry if there are some regressions.
Everything will be more stable in a few days.

‘btw : what is your platform? iOS, Android or web ?

**Comment by Larpoux** [comment]
Flutter Sound 9.9.0 is released. Sorry for the regression we had on 9.8.
Of course tell me if any problem

**Comment by SheepYang1993** [comment]
> Flutter Sound 9.9.0 is released. Sorry for the regression we had on 9.8. Of course tell me if any problem

thanks a lot. now it's works.
