### ISSUE TITLE
[BUG]:After upadting the latest version of flutter ,release build not building

### ISSUE THREAD

**Issue by atvbasha** [Canardoux/flutter_sound#1071]

**Comment by Larpoux** [comment]
?

**Comment by tan-yaka** [comment]
If you are getting the same build error as me :

```
Execution failed for task ':flutter_sound:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:<Path to app>/build/flutter_sound/intermediates/merged_res/release/values/values.xml:2536: AAPT: error: resource android:attr/lStar not found.
```

I had to edit `<...>/.pub-cache/hosted/pub.dev/flutter_sound-9.10.5/android/build.gradle` and change `compileSdkVersion 30` to `compileSdkVersion 34` to match my value in my app gradle config

**Comment by ETmanwenhan** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sound:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/hengry/Documents/repo/flutter/xxx/flutter_app/build/flutter_sound/intermediates/merged_res/release/values/values.xml:2536: AAPT: error: resource android:attr/lStar not found.

**Comment by Larpoux** [comment]
> If you are getting the same build error as me :
> 
> ```
> Execution failed for task ':flutter_sound:verifyReleaseResources'.
> > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
>    > Android resource linking failed
>      ERROR:<Path to app>/build/flutter_sound/intermediates/merged_res/release/values/values.xml:2536: AAPT: error: resource android:attr/lStar not found.
> ```
> 
> I had to edit `<...>/.pub-cache/hosted/pub.dev/flutter_sound-9.10.5/android/build.gradle` and change `compileSdkVersion 30` to `compileSdkVersion 34` to match my value in my app gradle config

This is not good if the default Android sdk is not correct. I am going to check this as soon as I will get my new computer (at the end of the week, I hope)

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。

**Comment by Larpoux** [comment]
I will check that, I promise. But it would be fantastic if someone does a Pull Request

**Comment by Larpoux** [comment]
Hi, guys and girls.
I checked your issue : the compiled SDK version is 34, since Flutter Sound v 11.2

### 9.11.2

- Android build.gradle: compileSdk = 34


You should use a recent Flutter Sound version
