### ISSUE TITLE
[ENH]: Can we upgrade the web library to version v1.0.0

### ISSUE THREAD

**Issue by hhcme** [Canardoux/flutter_sound#1077]
![2011724294253_ pic](https://github.com/user-attachments/assets/bcf6e845-1d9d-4a97-9512-1252a0c2fe7e)

Can we upgrade the web library to version v1.0.0

**Comment by hhcme** [comment]
Picture content：
/Users/hhc/Desktop/flutter/flutter/bin/flutter --no-color pub upgrade
Resolving dependencies...
Because flutter_sound >=9.11.2 depends on flutter_sound_web 9.11.2 which depends on web ^0.5.0, flutter_sound >=9.11.2 requires web ^0.5.0.
And because cached_network_image >=3.4.1 depends on cached_network_image_web ^1.3.1 which depends on web ^1.0.0, flutter_sound >=9.11.2 is incompatible with cached_network_image >=3.4.1.
So, because drawing_ai depends on both cached_network_image ^3.4.1 and flutter_sound ^9.11.2, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Consider downgrading your constraint on flutter_sound: flutter pub add flutter_sound:^9.8.1
* Consider downgrading your constraint on cached_network_image: flutter pub add cached_network_image:^3.4.0
Process finished with exit code 1

**Comment by hhcme** [comment]
It will also affect the upgrade of file_picker to the latest v8.1.2


Because flutter_sound >=9.11.2 depends on flutter_sound_web 9.11.2 which depends on web ^0.5.0, flutter_sound >=9.11.2 requires web ^0.5.0.
And because file_picker >=8.1.0 depends on web ^1.0.0, flutter_sound >=9.11.2 is incompatible with file_picker >=8.1.0.
So, because drawing_ai depends on both file_picker ^8.1.2 and flutter_sound ^9.11.2, version solving failed.

**Comment by Larpoux** [comment]
I am going to look if possible to depend on Web 1.0.0

i will try but not sure to success because Web 1.0.0 is very different than the previous versions.

**Comment by hhcme** [comment]
Thank you very much. You worked hard.
