### ISSUE TITLE
[BUG]: onProgress not being called

### ISSUE THREAD

**Issue by bradintheusa** [Canardoux/flutter_sound#1080]
## Severity
- Minor issue

## Platforms you faced the error 
- Android
- Real device
- 
**Describe the bug**
In the demo app the `onProgress` is not being called and the progress does not show for the play and record samples.

**To Reproduce**
Run the demo app on an Android Device.

**Comment by bradintheusa** [comment]
Some screenshots from the demo app showing progress not firing on some samples but working in the main demo

![Screenshot_20240822-233329](https://github.com/user-attachments/assets/74227c2b-5f81-4671-99bc-b265b00871df)
![Screenshot_20240822-233310](https://github.com/user-attachments/assets/88f49493-7cdd-48b9-991f-58d39d309bf7)
![Screenshot_20240822-233203](https://github.com/user-attachments/assets/c51cf39e-56cf-46c5-a9a3-bd678bbec8d3)
![Screenshot_20240822-233101](https://github.com/user-attachments/assets/565eb0e5-5b38-4105-82e9-ca861b30fba3)

**Comment by Larpoux** [comment]
The example tried to show how to parameter the frequency of the call back.
The cursor allows to choose this frequency. When the cursor is 0 (the default), there is no callback

**Comment by bradintheusa** [comment]
oh, I see that code now. Sorry for wasting your time.
