### ISSUE TITLE
[BUG]:7.8.4 pod install  cannot install tau_core

### ISSUE THREAD

**Issue by leave-alone** [Canardoux/flutter_sound#1083]
Installing tau_core (7.8.4)
     > Git download
     > Git download
         $ /usr/bin/git clone https://github.com/canardoux/tau_core.git /var/folders/v2/n4yzx4t57ls_18p0lkznd41c0000gn/T/d20240830-83744-1b124if --template= --single-branch --depth 1 --branch 7.8.4

    [!] Error installing tau_core
    [!] /usr/bin/git clone https://github.com/canardoux/tau_core.git /var/folders/v2/n4yzx4t57ls_18p0lkznd41c0000gn/T/d20240830-83744-1b124if --template= --single-branch --depth 1 --branch 7.8.4

    Cloning into '/var/folders/v2/n4yzx4t57ls_18p0lkznd41c0000gn/T/d20240830-83744-1b124if'...
    warning: Could not find remote branch 7.8.4 to clone.
    fatal: Remote branch 7.8.4 not found in upstream origin

**Comment by Larpoux** [comment]
Why are you trying to install tau_core 7.8.4
This project is deprecated.
You must do : 
```sh
git clone --recursive git@github.com:Canardoux/flutter_sound.git
```
