### ISSUE TITLE
[HELP]: I cannot play incoming voice packets over UDP.

### ISSUE THREAD

**Issue by MuhammedSaygili** [Canardoux/flutter_sound#1093]
Hi @Larpoux ,
Firstly, I am somewhat new and inexperienced with Flutter. I want to play audio data received over UDP, but I haven't succeeded yet. The incoming audio is 10 kHz and 16-bit. Initially, since streaming didn't come to mind, I tried playing it in parts as a buffer. Later, I attempted streaming but was unable to make it work. The audio packets arriving over UDP are coming as 200 200. Because it's 8-bit, I believe they are arriving as 400 400. In the code example below, I managed to convert the incoming packets to sound, but there are many interruptions and a slight delay. Could you help me with this?
```
//UDP Listener
void startBroadcastListener() async {
    RawDatagramSocket.bind(InternetAddress.anyIPv4, 2128).then((RawDatagramSocket socket) {
      print('UDP broadcast listener started...');
      socket.broadcastEnabled = true;
      socket.listen((RawSocketEvent event) {
        if (event == RawSocketEvent.read) {
          Datagram? datagram = socket.receive();
          if (datagram != null && datagram.data.length > 10) {
            Uint8List rawData = datagram.data;
            List<int> pcmData = convertToPCM16(rawData);
            recordData(pcmData);
            print(pcmData);
          }
        }
      });
    });
  }
//Convert Fn
  List<int> convertToPCM16(Uint8List rawData) {
    List<int> pcmData = [];
    for (int i = 0; i < rawData.length; i += 2) {
      int lsb = rawData[i];
      int msb = rawData[i + 1];
      int sample = (msb << 8) | lsb;
      if (sample >= 0x8000) {
        sample -= 0x10000; // signed 16-bit conversion
      }
      pcmData.add(sample * 150); // sound level x 150
    }
    return pcmData;
  }
  //Play
  void recordData(List<int> value) {
    _audioBuffer.addAll(value);
    if (!_isPlaying) {
      playAudioFromBuffer();
    }
  }

  void playAudioFromBuffer() async {
    if (!_isPlaying && _audioBuffer.isNotEmpty) {
      _isPlaying = true;
      int playLength = _audioBuffer.length;
      Uint8List audioData = Uint8List(playLength * 2);
      for (int i = 0; i < playLength; i++) {
        audioData[i * 2] = _audioBuffer[i] & 0xFF;
        audioData[i * 2 + 1] = (_audioBuffer[i] >> 8) & 0xFF;
      }
      print("Playing ${audioData.length} bytes of audio");
      await _player!.startPlayer(
        fromDataBuffer: audioData,
        codec: Codec.pcm16,
        sampleRate: 11000,
        numChannels: 1,
        whenFinished: () {
          setState(() {
            if (_audioBuffer.isNotEmpty) {
              _audioBuffer.removeRange(0, playLength);
            _isPlaying = false;
            }
          });
        },
      );
    }
  }
  
```

**Comment by Larpoux** [comment]
Just a moment : I am going to look to your request.

Note: Playing from a Stream is really what you must do.

**Comment by Larpoux** [comment]
I am not familiar with your UDP server, but I think that if you receive your packets as Uint8List, there is nor reason to convert them to integer and then convert your integers back to UInt8List for Flutter Sound.

**Comment by Larpoux** [comment]
There two main formats for PCM audio : 
- Int16
- Float32

Actually Flutter Sound just handle Int16.
But you are in luck if your server send you Int16

Flutter Sound request a Stream UInt8List, just as a way to handle binary data. (with two Uint8 for each Int16).
I have the feeling that it is the same for your server

**Comment by Larpoux** [comment]
You probably not have to bother with BigEndian and littleEndian.
Nowadays, almost everybody use LittleEndian. So don't care with that

**Comment by MuhammedSaygili** [comment]
First of all, thank you very much. To amplify the sound, I converted it to 16-bit and then reduced it, though I am fully aware that this is completely ridiculous. As you mentioned, my server sends 16-bit audio as 8-bit LSB and MSB. However, I am unable to manage the streaming process correctly.

**Comment by Larpoux** [comment]
What is exactly your issue ? A problem with the CPU overload and latency ?

I think that it will be hard to solve that, because at 10 000 Hz, your receive VERY MUCH data.
You want to process them byte per byte and it is MUCH work.

You could do that inside the iOS/Android code itself, but it will be difficult to achieve that.
I don't think that you should consider that solution.

**Comment by MuhammedSaygili** [comment]
> What is exactly your issue ? A problem with the CPU overload and latency ?
> 
> I think that it will be hard to solve that, because at 10 000 Hz, your receive VERY MUCH data. You want to process them byte per byte and it is MUCH work.
> 
> You could do that inside the iOS/Android code itself, but it will be difficult to achieve that. I don't think that you should consider that solution.

My main problem isn't the delay itself—the delay is very short. The code I provided essentially operates without streaming, meaning I believe there's a delay because I stop and start playback each time. I haven't been able to convert the packets received from UDP into sound using a stream, which is the solution I actually need.

**Comment by Larpoux** [comment]
OK. I am going to look better

**Comment by MuhammedSaygili** [comment]
Also, the sound comes in single channel.

**Comment by Larpoux** [comment]
Your code is incorrect : it's impossible to open a Player for each packet.
You definitely need to open a player from Stream and just feed the stream when you have handled your packet

**Comment by Larpoux** [comment]
Recently I update Flutter Sound to handle stereo with streams. But you will not be able to have more than 2 channels on Android

**Comment by MuhammedSaygili** [comment]
> Your code is incorrect : it's impossible to open a Player for each packet. You definitely need to open a player from Stream and just feed the stream when you have handled your packet

I tried this but I couldn't get any sound from the device. I guess I didn't do it right and deleted the codes. I'll try again.

> Recently I updated Flutter Sound to handle stereo with streams. But you will not be able to have more than 2 channels on Android

This is not my problem at all

**Comment by MuhammedSaygili** [comment]
Is it possible for you to share resources that can help me? My main profession is electronics and embedded software, so I'm having a hard time.

**Comment by Larpoux** [comment]
You can look to the example "Play From Stream" .
It is very simple. Just a few lines of code.
If you have problems to play your stream, I will give you some help to debug.
I am confident that you will success, because you are actually able to have some sound when you play from buffer.

**Comment by Larpoux** [comment]
There is two variants of the example
- play from stream with back pressure 
- Play from stream without back pressure 

you are concerned by the "without back pressure" case because you probably not control the UDP server. You don’t have a protocol to tell your server when you are ready to play but your buffers are almost empty.

It will be simpler for you. Internally, the Dart stream will buffer the data if the server send data faster than you can play them. If the server don’t send the data fast enough, you will have some blanks. You can’t do anything if your server is too slow, of course.

**Comment by MuhammedSaygili** [comment]
If the server is slow or too fast, I can adjust it with the sampling rate. Also, the server is actually an electronic hardware and sends sound in real time by doing analog sampling. The sending rate is stable and always the same. It can also tell when it will start and when it will end.

**Comment by MuhammedSaygili** [comment]
I'm asking to confirm—if I understood correctly, you recommend using "without back pressure" because "with back pressure" is suitable for continuous streams and would cause gaps for streams coming from UDP, right?

**Comment by Larpoux** [comment]
Back pressure is when you have a protocol to tell the server that your buffers are almost empty and you want some more data. In this case, the server is completely handled by your app.

There are several way to solve the problem of synchronization between the server and the app.
If your audio sessions are short (a dozen of seconds), and if it is OK for your app, you can for example wait a short time (100 ms, for example) before starting your playback. The audio data will be buffered by your stream during those 100ms, and you will be sure to have enough data without being too short on your buffers.

You know your app better than me, of course.

**Comment by Larpoux** [comment]
Synchronization between two machines needs a protocol.
Synchronization is necessary if your sessions are long, and you don't want any latency. If your server is too fast, after some times, you have the risk to have more and more data waiting in your buffers and the latency will be more and more important.
If your server is too slow, you risk to be short on buffers and you risk to have nothing to play from time to time.

**Comment by MuhammedSaygili** [comment]
It's actually a very sound approach, but synchronization with the server is somewhat challenging. However, I managed to resolve the issue using the "without back pressure" example. There's only a minor problem, which might be somewhat related to the audio and could also be caused by the server. Thank you very much.

Additionally, I'm experiencing problems with capturing audio from the microphone via a stream. There's an error in the recordToStream example that I mentioned above. How should I proceed regarding this?

**Comment by Larpoux** [comment]
Yes, I am going to see that. Probably something very simple to fix. Just a moment...

**Comment by MuhammedSaygili** [comment]
btw the version i used is ^9.2.13

**Comment by Larpoux** [comment]
Your version is too old. Why do you use a so old version ?

**Comment by MuhammedSaygili** [comment]
Actually, I was using a newer version, but to ensure it worked more accurately, I based it on the pubspec file from the old example folder. I just realized now that the version is outdated; it had slipped my mind.

**Comment by MuhammedSaygili** [comment]
I updated my version and will be switching to microphone streaming shortly, but I noticed that there are no issues with the UDP server and the audio. I hope that my problem becomes evident in this MP3 file. When I gather the same audio data from the terminal and convert it to a WAV file using Python, there are no problems with the audio.

[Sound File (Google Drive)](https://drive.google.com/file/d/1238pCwZFZEgUvFk6kem5zxkU15kDDOU0/view?usp=sharing)

**Comment by MuhammedSaygili** [comment]
I added UDP reception to the "play stream without back pressure" example, and the received UDP data is being added in this way.


```
    feedHim(datagram.data);
    //if (_mPlayer != null) {
    // We must not do stopPlayer() directely //await stopPlayer();
    _mPlayer.foodSink!.add(FoodEvent(() async {
      //await _mPlayer.stopPlayer();
      //FlutterSoundPlayer().logger.i("MARKER!");

      setState(() {});
    }));
```

**Comment by MuhammedSaygili** [comment]
Everything is great in terms of timing, but because of the play and stop operations, I'm not entirely sure how to eliminate these sounds that I believe are caused by them. If you listen to the audio file, you'll understand what I mean—these parasitic noises are not coming from the UDP server. Additionally, I have resolved the microphone streaming issue; I'm capturing the stream and sending it via UDP, but I haven't yet proceeded to modulate it on the UDP server. I don't anticipate any problems arising from this.

[Sound File (Google Drive)](https://drive.google.com/file/d/1238pCwZFZEgUvFk6kem5zxkU15kDDOU0/view?usp=sharing)

**Comment by Larpoux** [comment]
> but because of the play and stop operations

Which `play and stop` ?

**Comment by Larpoux** [comment]
can you send me your actual code ? I am lost.

**Comment by MuhammedSaygili** [comment]
There is no stopping and starting in the code, but I definitely think there is a gap between the two feeds. It must be very small because there is almost no delay, but I believe this is causing the sound. This is just the first scenario that comes to mind. The code is below.
```
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_sound/flutter_sound.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:logger/logger.dart' show Level;

//import 'package:logger/logger.dart';

/*
 *
 * A very simple example showing how to play Live Data without back pressure.
 * A very simple example showing how to play Live Data without back pressure.
 * It feeds a live stream, without waiting that the Futures are completed for each block.
 * This is simpler because the App does not need to await the playback for each block before playing another one.
 *
 *
 * This example get the data from an asset file, which is completely stupid :
 * if an App wants to play an asset file he must use "StartPlayerFromBuffer().
 *
 * Feeding Flutter Sound without back pressure is very simple but you can have two problems :
 * - If your App is too fast feeding the audio channel, it can have problems with the Stream memory used.
 * - The App does not have any knowledge of when the provided block is really played.
 * If he does a "stopPlayer()" it will loose all the buffered data.
 *
 * This example uses the ```foodEvent``` object to resynchronize the output stream before doing a ```stop()```
 *
 */

///
const int tSampleRate = 10000;

///
const int tBlockSize = 200;

///
typedef Fn = void Function();
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'UDP Listen',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const LivePlaybackWithoutBackPressure(),
    );
  }
}
/// Example app.
class LivePlaybackWithoutBackPressure extends StatefulWidget {
  const LivePlaybackWithoutBackPressure({super.key});

  @override
  State<LivePlaybackWithoutBackPressure> createState() =>
      _LivePlaybackWithoutBackPressureState();
}

class _LivePlaybackWithoutBackPressureState
    extends State<LivePlaybackWithoutBackPressure> {
  final FlutterSoundPlayer _mPlayer = FlutterSoundPlayer(logLevel: Level.off);
  
  bool _mPlayerIsInited = false;
  double _mSpeed = 100.0;
  late Uint8List data;

  Future<void> initPlayer() async {
    await _mPlayer.openPlayer();
    _mPlayerIsInited = true;
    assert(_mPlayerIsInited && _mPlayer.isStopped);
    await _mPlayer.startPlayerFromStream(
        codec: Codec.pcm16,
        numChannels: 1,
        sampleRate: tSampleRate,
        bufferSize: 1000,
        whenFinished: () {
          //FlutterSoundPlayer().logger.i("FINISHED!");
        });
    //data = await getAssetData('assets/samples/sample.pcm');
    
    setState(() {
      _mPlayerIsInited = true;
    });
  }

  @override
  void initState() {
    super.initState();
    // Be careful : openAudioSession return a Future.
    // Do not access your FlutterSoundPlayer or FlutterSoundRecorder before the completion of the Future
//    _mPlayer.openPlayer().then((value) {
//      setState(() {
//        _mPlayerIsInited = true;
//      });
//    });
    initPlayer();
    startBroadcastListener();
  }

  @override
  void dispose() {
    //stopPlayer();
    _mPlayer.closePlayer();
    super.dispose();
  }

  // -------  Here is the code to play Live data without back-pressure ------------

  void feedHim(Uint8List data) {
    var start = 0;
    var totalLength = data.length;
    while (totalLength > 0 && !_mPlayer.isStopped) {
      var ln = totalLength > tBlockSize ? tBlockSize : totalLength;
      _mPlayer.foodSink!.add(FoodData(data.sublist(start, start + ln)));
      totalLength -= ln;
      start += ln;
    }
  }

  void play() async {

    //}
  }

  // --------------------- (it was very simple, wasn't it ?) -------------------

  Future<Uint8List> getAssetData(String path) async {
    var asset = await rootBundle.load(path);
    return asset.buffer.asUint8List();
  }

  Future<void> stopPlayer() async {
    //if (_mPlayer != null) {
    await _mPlayer.closePlayer();
    setState(() {});
  }

  Future<void> setSpeed(double v) async // v is between 0.0 and 100.0
  {
    v = v > 200.0 ? 200.0 : v;
    _mSpeed = v;
    setState(() {});
    await _mPlayer.setSpeed(
      v / 100,
    );
  }

  Fn? getPlaybackFn() {
    if (!_mPlayerIsInited) {
      return null;
    }
    return _mPlayer.isStopped
        ? play
        : () {
            stopPlayer().then((value) => setState(() {}));
          };
  }

List<int> convertToPCM16(Uint8List rawData) {
    List<int> pcmData = [];
    for (int i = 0; i < rawData.length; i += 2) {
      int lsb = rawData[i];
      int msb = rawData[i + 1];
      int sample = (msb << 8) | lsb;
      if (sample >= 0x8000) {
        sample -= 0x10000; // signed 16-bit conversion
      }
      pcmData.add(sample);
    }
    return pcmData;
  }


void startBroadcastListener() async {
    RawDatagramSocket.bind(InternetAddress.anyIPv4, 2128).then((RawDatagramSocket socket) {
      print('UDP broadcast dinleyici başlatıldı...');
      socket.broadcastEnabled = true;

      socket.listen((RawSocketEvent event) {
        if (event == RawSocketEvent.read) {
          Datagram? datagram = socket.receive();
          if (datagram != null) {
            if (datagram.data.length < 10){
              var command = utf8.decode(Uint8List.fromList(datagram.data));
              if (command == "RXTRUE"){

              } else if (command == "RXFALSE"){

              }
              print(command);
            } else {
                  List<int> pcmData = convertToPCM16(datagram.data); //just debug
                  print(pcmData);//just debug
                    feedHim(datagram.data);
                    //if (_mPlayer != null) {
                    // We must not do stopPlayer() directely //await stopPlayer();
                    _mPlayer.foodSink!.add(FoodEvent(() async {
                      //await _mPlayer.stopPlayer();
                      //FlutterSoundPlayer().logger.i("MARKER!");

                      setState(() {});
                    }));
            }
          }
        }
      });
    });
  }


  // ----------------------------------------------------------------------------------------------------------------------

  @override
  Widget build(BuildContext context) {
    Widget makeBody() {
      return Column(children: [
        
      ]);
    }

    return Scaffold(
      backgroundColor: Colors.blue,
      appBar: AppBar(
        title: const Text('Sound Check'),
      ),
      body: makeBody(),
    );
  }
}
```

**Comment by Larpoux** [comment]
The code seems correct.
Of course `setSpeed()` and `getAssetData()` are not useful.
Also, are you sure of 'numberOfChannels`?

Also I have some doubt on `RXFALSE`, ...
If your server sends a kind of commands, it should be the noises that you hear.
I am not very expert on UDP, but I think that there is no garanti that you receive your data from your UDP packet datagram per datagram.
If this is true, your test ont the length >. 10 could be incorrect.

**Comment by Larpoux** [comment]
I really think that you don’t receive datagrams from your server, but a stream of data on a socket. Because you don’t have any access to the datagrams, you cannot test the length of them (<10) and filter the commands (RX) that are inserted by your server in the middle of the stream.
You must implement a kind of protocol with your server allowing you to retrieve the RX datagrams which are in the middle of your data, and filter them.

**Comment by MuhammedSaygili** [comment]
RXTRUE and RXFALSE are sent at the beginning and end to indicate that the transmission has started and ended. Apart from these two commands, only audio data is received, and the packet size consistently remains fixed at 400. Since these packets are audio packets, they are ready to be converted to sound without requiring additional processing or parsing. Additionally, when I repeatedly collected and tested the incoming packets in the terminal and converted them to sound in a different environment, they played correctly, unlike what I provided in the link to you. Perhaps at this point, some packets are not arriving on time, but even if the audio comes with some noise, it can be heard normally with very low latency. This means that if there is packet delay, it could be heard as being out of sync.

**Comment by Larpoux** [comment]
I don’t think that you control the datagrams and there length.
Your server sends datagrams but you receive a stream.
You have no way to know the length of the datagrams which was sent by your server.
You just receive a stream of data, chunk per chunk. Not datagrams per datagrams.
There is several layers of software in the os which eventually combines the datagrams to a stream. You don’t access the original datagrams. You just receive packets which are not datagrams.

Any way, this is your problem, now. If you have other issues with Flutter Sound, don’t hesitate to post a new request for help

**Comment by MuhammedSaygili** [comment]
Thank you for your help and guidance.
