### ISSUE TITLE
[HELP]: Player stops playing when I start recording

### ISSUE THREAD

**Issue by Takrem1** [Canardoux/flutter_sound#1098]
## Here is my question :

Hey, I want to record an play audio at the same time.

Player:
I have a websocket via which I receive pcm16 audio data. I write these directly into the player and they are also played successfully.

Recorder:
I want to record pcm16 packets with the FlutterSoundRecorder and send them to a server via the websocket.

Since the whole thing is supposed to be a real-time communication, the playback and recording must take place simultaneously.

Both work fine on their own, but as soon as I start both at the same time, the player stops playing audio. It feels like the recorder is somehow terminating the player or something. As soon as I stop recording, the player starts playing audio again. 
What could be the reason for this?

I am currently testing this on android

**Comment by Larpoux** [comment]
It should be ok to open a player and a recorder at the same time. Several flutter sound users do that with success.

could you send your logs?

**Comment by Larpoux** [comment]
This is good news 👍
