### ISSUE TITLE
[HELP]: Why is `event.decibels` not providing a value?

### ISSUE THREAD

**Issue by LdzLq** [Canardoux/flutter_sound#1103]
I need Help for :

- Using the API:
 1. FlutterSoundRecorder().startRecorder()
 2.  FlutterSoundRecorder().onProgress!.listen((e){})

- Generate an Android App 
- not work code: 
```
 _recorder.onProgress!.listen((e) {
        print('Current dB: ${e.decibels}');
        print('onProgress called'); 
        if (e.decibels != null) {
          _currentDb.value = e.decibels!;
          print('Current dB: ${e.decibels}');
        }
```
-additions
I am certain that the recording permissions are not an issue, and when I save the audio recorded by `startRecorder()` to the local storage, it plays with sound using a media player.

**Comment by Larpoux** [comment]
Did you call `_recorder.setSubscriptionDuration(Duration(milliseconds: 100))` ?
