### ISSUE TITLE
[BUG]:Audio can't mix with another app on Ios

### ISSUE THREAD

**Issue by WNizard** [Canardoux/flutter_sound#1111]
## Flutter Sound Version : 9.16.3

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

├── flutter_sound 9.16.3
│   ├── flutter_sound_platform_interface...
│   ├── flutter_sound_web 9.16.3
│   │   ├── flutter_sound_platform_interface...
├── flutter_sound_platform_interface 9.16.3
----------------------------------------------------------

## Severity

- Crash ? kinda

- Result is not what expected ? yes

- Cannot build my App ? no

- Minor issue ? no

--------------------------------------------------------

## Platforms you faced the error 

- iOS ? yes

- Android ? half of it

- Real device ? yes

------------------------------------------------

**Describe the bug**
IOS: When I play my audio everything works as expected, but then, when I go on background and that I start for example a youtube video, my audio is not mixing with youtube and will never start again even if I turn it off and on again.
The problem with this issue is that I don't have any exception nor error, my stream is just stopping and not starting ever again.
Android: it's mixing, but when I turn it off I can't turn it on again because I think that the audioPlayer doesn't want to be closed cause it's in an unfinished state

**To Reproduce**
-Start a flutterSoundplayer:
`
        await soundPlayer.openPlayer();
        await soundPlayer.startPlayerFromStream(
          codec: Codec.pcm16,
          numChannels: BabyMonitorCallService.channels,
          sampleRate: BabyMonitorCallService.sampleRate,
        );
`
-go on youtube
-play a video
-try to hear your stream
----------------------------------------------

However, because there is no error, I don't have any interesting logs.
I still can receive my audio packets from my audio socket during this bug, but these buffers are never played.

I can show you my AudioSession configuration thought:

`Future<void> configureAudioSession() async {

      final session = await AudioSession.instance;
      await session.configure(AudioSessionConfiguration(
        avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
        avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.defaultToSpeaker | 
                                       AVAudioSessionCategoryOptions.mixWithOthers | 
                                       AVAudioSessionCategoryOptions.allowBluetooth | 
                                       AVAudioSessionCategoryOptions.interruptSpokenAudioAndMixWithOthers,
        avAudioSessionMode: AVAudioSessionMode.voiceChat,
        avAudioSessionRouteSharingPolicy: AVAudioSessionRouteSharingPolicy.defaultPolicy,
        avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.notifyOthersOnDeactivation,
        androidAudioAttributes: const AndroidAudioAttributes(
          contentType: AndroidAudioContentType.speech,
          flags: AndroidAudioFlags.none,
          usage: AndroidAudioUsage.voiceCommunication,
        ),
        androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
        androidWillPauseWhenDucked: false, // Change this to false to allow mixing
      ));
      await session.setActive(true);
  }
`

-----------------------------------------------------------------

**Comment by WNizard** [comment]
For the logs, as I said, I don't have anything interesting:
the moment where they disappear is at the exact second where I click play on the youtube video
![Screenshot 2024-10-25 at 12 44 28](https://github.com/user-attachments/assets/e43c7c05-3792-4be7-a139-05f360304dba)

**Comment by WNizard** [comment]
Also, when I try this:
`Future<void> _listenForAudioInterruptions() async {
    final session = await AudioSession.instance;
    session.interruptionEventStream.listen((event) {
      if (event.begin) {
        switch (event.type) {
          case AudioInterruptionType.duck:
            _handleDuckInterruption();
            break;
          case AudioInterruptionType.pause:
          case AudioInterruptionType.unknown:
            _handlePauseInterruption();
            break;
        }
      } else {
        switch (event.type) {
          case AudioInterruptionType.duck:
            _handleUnduckInterruption();
            break;
          case AudioInterruptionType.pause:
          case AudioInterruptionType.unknown:
            _handleResumeInterruption();
            break;
        }
      }
    });

    session.becomingNoisyEventStream.listen((_) {
      _handleBecomingNoisy();
    });
  }

  void _handleDuckInterruption() {
    DebugService.printDebug("Audio ducked");
  }

  void _handlePauseInterruption() {
    soundPlayer.pausePlayer();
  }

  void _handleUnduckInterruption() {
    DebugService.printDebug("Audio unducked");
  }

  void _handleResumeInterruption() {
    DebugService.printDebug("Audio resumed after interruption");
    if (_isSoundPlayerAcquired) {
      soundPlayer.resumePlayer();
    }
  }
  }`
  this is what happens instantly when the interruption stops
![Screenshot 2024-10-25 at 14 42 39](https://github.com/user-attachments/assets/2e605344-4df2-421b-bcca-1a3da019b95e)

**Comment by WNizard** [comment]
Update about the past week:
I changed my way to configure the audio session, now I do it  just before starting the stream, before it was during the class's initialization.
Now my stream is mixable with Youtube.
However some sounds like a timer on IOS will break my stream just like youtube use to do.
I changed my way to handle interruptions:

`            session.interruptionEventStream.listen((event) async {
              if (event.begin) {
            switch (event.type) {
              case AudioInterruptionType.duck:
                soundPlayer.setVolume(0.5);
                break;
              case AudioInterruptionType.pause:
              case AudioInterruptionType.unknown:
                await soundPlayer.pausePlayer();
                break;
           }
          } else {
            switch (event.type) {
                case AudioInterruptionType.duck:
                  soundPlayer.setVolume(1.0);
                  break;
                case AudioInterruptionType.pause:
                case AudioInterruptionType.unknown:
                  await disposeSoundPlayer();
                  globals.needToAcquireSoundPlayer = true;
                    break;
            }
          }
        });`
I basically destroy the player and create a brand new one at the end of the interruption. But I feel that this is not viable and I need to find a better way to resume my stream to optimize my app.

**Comment by Larpoux** [comment]
@WNizard : I am going for lunch. I will look to your issue this afternoon

**Comment by Larpoux** [comment]
How do you call YouTube? In the same app or in another app?
(On iOS there is only one audio session by app. This session is shared by every body inside the app.

**Comment by WNizard** [comment]
Hi! So what I do is that I just start my call (so it's a call from a tcpSocket from a babyphone to my app) and then I put the app on background (the call is still working nothing breaks at this point) and then I go on youtube and click on a video, the sound is suppose to be mixed with the call, but no, it's interrupted, and then, when I quit youtube, the audio is not working no more and I believe that the audioPlayer is stuck in await feedfromstream (with await!!!)

**Comment by Larpoux** [comment]
I will try to think to your issue tomorrow.
But I am surprised by your problem: it seems to me that it is something with the audio session management. Several years ago, flutter sound tried to manage the audio session. But not anymore: we had too many problems with iOS, because there is only one audio session for each app. Some users complained that flutter sound was incompatible with others audio plugins. So we decided to delegate the audio session management to another third party lib, like flutter_audio_session.

Actually, there is not any line of code in flutter sound about session management.
It is possible (but surprising) that the problem is inside YouTube, flutter_audio_session, or even inside iOS itself.

**Comment by Larpoux** [comment]
I am surprised that you use `feedFromStream`. If I understand correctly, you are playing audio data from a remote server.
Perhaps you should not use `playback with back pressures but `playback without back pressure`. Because you probably can’t control the data flow from your server.
Your code will be much simpler, and you will not have any problem with locked await.

Just push your server data to the stream sink, without await. Please tell me if I am confusing.

**Comment by WNizard** [comment]
I will for sure try this on monday! I'Il get back to you asap thanks for the support

**Comment by Larpoux** [comment]
Play from stream with back pressure was probably a bad idea from me:
- it is more complicated 
- It is perhaps buggy 
- Almost every body use it to play data from a remote server without any flow control 
- I am not able to port this feature to flutter sound 10.0

**Comment by WNizard** [comment]
Hey @Larpoux I'm currently checking the example /live_playback_without_back_pressure.dart,
in this example, the data is directly created from a file, which is confusing to me cause you then don't have to loop on anything, and, also, do I have to copy the "feedHim" method?

**Comment by WNizard** [comment]
Update: I transitioned to the foodSink method, however my interruptions issues are still occurring. I don't know how to solve them but at least now I'm not stuck in feedFromStream :)

**Comment by WNizard** [comment]
@Larpoux Also, I figured that if my phone is connected to a bluetooth device,  the first few frames are played, and then nothing else however I know for a fact that they are received and tried to be played, the lign:
        soundPlayer.foodSink?.add(FoodData(samples.buffer.asUint8List()));
is executed, but the sound is not played, Imma try to debug this and figure this out!
