### ISSUE TITLE
[HELP]: Can I get the PCM when record to aac?

### ISSUE THREAD

**Issue by abellee** [Canardoux/flutter_sound#1121]
I wanna get the PCM data when record to file, PCM data for painting wave form and the aac file will be uploaded to the server.
Can I do that?

**Comment by Larpoux** [comment]
It will be easy to do that with flutter sound 10.0
Unfortunately I don’t think it is simple with flutter sound 9.x

**Comment by Larpoux** [comment]
Perhaps you can record to a pcm stream, and before sending the data to your server you will have to code them to aac with another lib like flutter ffmpeg

**Comment by Larpoux** [comment]
Flutter Sound v10.0 will be based on the [W3C Web Audio API recommendation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API).
This API is terrific. Very, very powerful.
If you look [to this](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API), you will see that this example is very closed from what you try to do.

Flutter Sound v10.0 will be released sometimes next year. I am busy working on it but the dev are slow.
In the mean time, you can have a look to [lab_sound_flutter](https://github.com/xioxin/lab_sound_flutter), but I don't guarantee that this product is good for you : 
- It does not seem to be well maintained
- It does not follow correctly the W3C recommendation
- I am not sure if it is really able to output a AAC file (?)

**Comment by abellee** [comment]
thx so much.
otherwise, I do feel you are a very nice guy!!
