### ISSUE TITLE
startPlayer incorrectly appends tmp folder when path supplied (iOS)

### ISSUE THREAD

**Issue by ukrx-xamd** [Canardoux/flutter_sound#28]
### Version of flutter_sound
1.2.1

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] VS Code (version 1.30.2)
[✓] Connected device (2 available)

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Expect startPlayer to not append a tmp folder to the path supplied.

### Actual behavior
Tmp folder is appended to the path supplied - issue is in iOS. In Android it works correctly.

### Tested environment (Emulator? Real Device?)
iOS X , iOS 8,7, iphone SE + Live devices for the same 

### Steps to reproduce the behavior
Supply a path to startPlayer.

I have supplied two screenshots that shows the place in iOS which is incorrect. In Android you handle this correctly and do not append a tmp folder.

I have created an AudioView widget that encapsulates the Flutter Sound functionality - in the constructor we can go into automatic play mode if **playerBytes** is not null. In which case we take the bytes passed to this class and write out in a temp folder - the workaround in iOS is not to set the path to _tuple.playbackFile:

### Workaround

  AudioView(
      {this.playerMode = false, this.playerBytes, this.autoPlay = false}) {
    /// If we want to display the audio and operate in playback mode ...
    if (playerBytes != null) {
      var tmp = Directory.systemTemp;
      String fileExtension;
      print(tmp.path);
      debug('--Player to play sound file--');

      if (defaultTargetPlatform == TargetPlatform.android) {
        debug('Android');
        fileExtension = 'mp4';
      } else if (defaultTargetPlatform == TargetPlatform.iOS) {
        debug('iOS');
        fileExtension = 'm4a';
      } else {
        debug(defaultTargetPlatform.toString());
        fileExtension = 'm4a';

        // just set to m4a
      }
      File f = File('${tmp.path}/playback2.$fileExtension');

      debug('New file = ${f.path}');
      f.writeAsBytesSync(playerBytes);
      // the iOS version of the Flutter sound adds the temp folder - so we just need to supply the file
      if (defaultTargetPlatform == TargetPlatform.iOS) {
        _tuple.playbackFile = 'playback2.$fileExtension';
      } else {
        _tuple.playbackFile = '${f.uri}';
      }
    } else {
      _tuple.playbackFile = null;
    }
  }

![sound - ios](https://user-images.githubusercontent.com/35817834/51206399-d9b8ba00-18ff-11e9-98d1-5b427a61277e.png)
![sound - android](https://user-images.githubusercontent.com/35817834/51206401-d9b8ba00-18ff-11e9-8d44-ea69c583fb45.png)

**Comment by hyochan** [comment]
@ukrx-xamd Nice catch! Could you give us a `PR` on this?

**Comment by ukrx-xamd** [comment]
Hi - yes agreed , this is not a show stopper and as mentioned - only affects iOS and is easily catered for on developer side, only pointed out as discrepancy between iOS and Droid implementation.

**Comment by hyochan** [comment]
@ukrx-xamd Thanks for additional explanation. If you think this is disturbance, you may create `PR` for this and I would merge this.

**Comment by ukrx-xamd** [comment]
No - all cool on this so no issues ... thanks

**Comment by linguitang** [comment]
I think para uri in startRecorder  should be just file name or file path,but not in android is file path, in ios is file name
