### ISSUE TITLE
Play audio in loop

### ISSUE THREAD

**Issue by karansingla007** [Canardoux/flutter_sound#675]
**Is your feature request related to a problem? Please describe.**
currently, there is no option to play audio in the loop.

**Describe alternatives you've considered**
currently, I played the same audio one by one on the function `whenFinished` of `startPlayer`.

**Comment by phamquoctrongnta** [comment]
@Larpoux 
Any update on this?

**Comment by Larpoux** [comment]
Sorry @phamquoctrongnta. No update for this requirement.
I don’t have time to spend on new features for Flutter Sound.
Actually I just work on bugs and look to the Pull Requests of other developers.

I am busy working on a new flutter plugin which will offer an implementation of the W3C Web Audio Api for Android and iOS. Then, Flutter Sound  V10 will be able to use this new plugin for everything about Streams (RecordToStreams, PlayFromStreams, PlayFromMic, …). This is a major work, so don’t expect a V10 soon.

**Comment by Larpoux** [comment]
@phamquoctrongnta .
There is no need for your feature request.
You can do yourself very simply:
```dart

for (var i = 0; i < 5; i++) {
  final Completer _completer = new Completer();
  StartRecorder (…
    whenFinished: {_completer.complete(0);}
    …
  );
  await _completer.future;
}
```
Of course don’t call startPlayer() in the WhenFinished callback.

**Comment by phamquoctrongnta** [comment]
@Larpoux 
Can I implement like this:
```
Future<void> _startBackgroundPlayer() async {
    _backgroundPlayer.startPlayer(
      fromDataBuffer: await _getAssetData(
        'assets/sound/background.wav',
      ),
      whenFinished: () {
        _startBackgroundPlayer();
      },
    );
  }
```
I called itself on `whenFinished` callback.
Is it okay?
In your above snippet, I don't understand: why for loop 5 times? What this  mean `_completer.complete(0);`?
P/S: Sorry for my bad English.

**Comment by Larpoux** [comment]
No, this is not OK to call startPlayer() int the call back, because you will have a recursion.
I loop 5 times because this is just an example how to play your sound 5 times. You can do what you want. Perhaps an infinite loop. Of course you will need a way to stop the loop when finished. Maybe when to close your form.

A way to finish the loop is something like 
```dart
while (!finished) {
```
When you want to finish playing, do something like : 
```dart
finished = true;
_completer.complete(0);
```

And you will have to put your completer outside your loop so you will have access to it.
This is not very hard...

**Comment by phamquoctrongnta** [comment]
@Larpoux 
In my snippet:
```
Future<void> _startBackgroundPlayer() async {
    _backgroundPlayer.startPlayer(
      fromDataBuffer: await _getAssetData(
        'assets/sound/background.wav',
      ),
      whenFinished: () {
        // How to create infinite loop?
      },
    );
  }
```
Sorry I don't understand how to create infinite loop?

**Comment by Larpoux** [comment]
```dart
bool finished = false;
while (!finished)  { // +++++++++++++++++++++++++ THIS IS THE LOOP
  final Completer _completer = new Completer();
  StartPlayer (…
    whenFinished: () {_completer.complete(0);}
    …
  );
  await _completer.future;
}
```

**Comment by Larpoux** [comment]
@phamquoctrongnta : 
I changed a little thing in version 9.5.0 : 
When the App specifies a callback `whenFinished`, Flutter Sound does not stop the player automatically but put the player in a pause state. The App can specify in its callback what it wants. Perhaps a `seekToPlayer(0); resume(); `

exemple:
```dart
player.startPlay( ... whenFinished: (){ player.seekToplayer(0); player.resume(); setState(){});});
```

This is simpler.

**Comment by phamquoctrongnta** [comment]
@Larpoux 
It's useful.
Thanks for this update.
Thanks for your support.
