### ISSUE TITLE
[BUG]: _myRecorder.onProgress not working

### ISSUE THREAD

**Issue by anokabb** [Canardoux/flutter_sound#750]
onProgress not working on all null safety releases

**Comment by danielwinkler** [comment]
Did you try setting `setSubscriptionDuration`?

**Comment by anokabb** [comment]
yes i set setSubscriptionDuration to 1s and it works perfectly thank you

**Comment by HasanAlyazidi** [comment]
It seems `onProgress` only works after calling `_mRecorder.setSubscriptionDuration()`
