### ISSUE TITLE
[HELP]:

### ISSUE THREAD

**Issue by zand-yasin** [Canardoux/flutter_sound#790]
I know here is not a good place for question for but it's pretty need, please someone help me :

-------------------------------------
 Here is my question :

- ### I just wanted to get the recorded voice file send it to a friend like a chat application, 
please how can i send the recorded audio to my friend?

Thanks alot for helping

**Comment by Larpoux** [comment]
My first reaction is to say that maybe Flutter is not the good framework to do a chat app.
Perhaps Blazor (or maybe MAUI?) is better for that.

But I am not at all an expert in this area, and I have no experience in Blazor, so I can be completely wrong.
Take this with pinch of salt : I am not an expert in this kind of things and I have no experience in Bazor.
If someone else has better informations, do not take into account what I am actually saying.

**Comment by zand-yasin** [comment]
> My first reaction is to say that maybe Flutter is not the good framework to do a chat app. Perhaps Blazor (or maybe MAUI?) is better for that.
> 
> But I am not at all an expert in this area, and I have no experience in Blazor, so I can be completely wrong. Take this with pinch of salt : I am not an expert in this kind of things and I have no experience in Bazor. If someone else has better informations, do not take into account what I am actually saying.

The issue is in get a recorded voice file for sending to the backend, chat application is fine!

**Comment by mhstoller** [comment]
This is definitely not the correct forum for this type of question as it's focused on flutter_sound as a plugin and it's capabilities.

You can use this example for how to record to a file: https://github.com/Canardoux/flutter_sound/blob/master/flutter_sound/example/lib/simple_recorder/simple_recorder.dart

There are more examples too, in the menu here: https://flutter-sound.canardoux.xyz/flutter_sound_examples_simple_recorder.html

Then you can use the file path to upload it to a backend server for your chat application. How to write backend code and upload the file is outside of the scope of this project, but you can use a library like [Dio](https://pub.dev/packages/dio) for the file upload from Flutter.

Best of luck.

**Comment by zand-yasin** [comment]
I have realized my issue, i just didn't knew files could be sending over the networks. and i implemented what i need.
Thank you all
