### ISSUE TITLE
[BUG]: flutter_sound when using the toSTream is extremely noisy

### ISSUE THREAD

**Issue by idanfi** [Canardoux/flutter_sound#801]
## Flutter Sound Version : 8.4.2

- **FULL** or **LITE** flavor ? FULL

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
>flutter pub deps | findstr flutter_sound
|-- flutter_sound 8.4.2
|   |-- flutter_sound_platform_interface 8.4.2
|   |-- flutter_sound_web 8.4.2
|   |   |-- flutter_sound_platform_interface...

----------------------------------------------------------

## Severity

- Crash ? NO

- Result is not what expected ? YES

- Cannot build my App ? NO

- Minor issue ? NO

--------------------------------------------------------

## Platforms you faced the error 

- Emulator ? YES
------------------------------------------------

**Describe the bug**
I am working on a project that is intended to be like an intercom with multiple devices, including my phone.
I want to use flutter_sound. To check that the streaming is working, I did a dummy implementation in which I register to the stream and write it to a file, and later play that file.
Sadly, When I try to play the file I hear 90% garbage and only if I shout during the recording I can here myself bad in the background.
Clearly I'm doing something wrong, because when I used the SimpleRecorder example, the quality was alright.

Here is the relevant snippet of record code that I did, the rest is just taken from the SimpleRecorder example app.

  // recording using a stream to a file (for now), later the stream will be sent online
  void record() {
    File f = File(_mPath);
    f.delete();
    IOSink fd = f.openWrite();
    StreamController<Food> recordStream = StreamController<Food>();
    recordStream.stream.listen((event) {
      fd.add((event as FoodData).data?.buffer.asUint8List() as Uint8List);
    });
    _mRecorder!.startRecorder(
      toStream: recordStream.sink,
      codec: _codec,
      audioSource: AudioSource.microphone,
    )
        .then((value) {
      setState(() {});
    });
  }

-----------------------------------------------------------------

Thanks!

**Comment by Larpoux** [comment]
Simple Recorder is a demo using StartRecorder (to File) and not StartRecorderToStream.
The implementation inside τ is very different for these two way of recording.

If you want to test Recording to Stream, try the example `Record to Stream` instead of the example `Simple Recorder`.

Note : I had fighted a long time with a bug inside the iOS implementation of audio streams, but never found the reason.
Actually there are little clicks inside the record. The result is not very good, but I do not think that the result is so bad that your are saying.

**Comment by idanfi** [comment]
Thanks, I used the implementation as in the 'Record to Stream' example and now it works fine.

Making it work on iOS is not mandatory at this point so I'm OK with that.
Closing this issue.
