### ISSUE TITLE
[BUG]:Build failed with an exception

### ISSUE THREAD

**Issue by lan2000** [Canardoux/flutter_sound#806]
## Flutter Sound Version : flutter_sound_lite: ^8.4.2

Logs
```
* What went wrong:
   > Could not resolve com.github.canardoux:flutter_sound_core:8.4.2.
     Required by:
         project :app > project :flutter_sound_lite
      > Could not resolve com.github.canardoux:flutter_sound_core:8.4.2.
         > Could not get resource 'https://dl.bintray.com/jetbrains/anko/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom'.
            > Could not HEAD 'https://dl.bintray.com/jetbrains/anko/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
```

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
```

**Comment by Stitch-Taotao** [comment]
When I add bellow native dependencies ,I got the error.(Meanwhile I add flutter `flutter_sound: ^8.4.2` in pubspec.yaml)
```
dependencies {
    implementation 'com.huawei.hms:push:4.0.2.300'
}
apply plugin: 'com.huawei.agconnect'
```
Error Log
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.canardoux:flutter_sound_core:8.4.2.
     Searched in the following locations:
       - http://maven.rongcloud.cn/repository/maven-releases/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
       - https://dl.google.com/dl/android/maven2/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
       - https://repo.maven.apache.org/maven2/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
       - http://developer.huawei.com/repo/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
     Required by:
         project :app > project :flutter_sound

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by Spencer231** [comment]
> When I add bellow native dependencies ,I got the error.(Meanwhile I add flutter `flutter_sound: ^8.4.2` in pubspec.yaml)
> 
> ```
> dependencies {
>     implementation 'com.huawei.hms:push:4.0.2.300'
> }
> apply plugin: 'com.huawei.agconnect'
> ```
> 
> Error Log
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:mergeDebugAssets'.
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
>    > Could not find com.github.canardoux:flutter_sound_core:8.4.2.
>      Searched in the following locations:
>        - http://maven.rongcloud.cn/repository/maven-releases/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - https://dl.google.com/dl/android/maven2/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - https://repo.maven.apache.org/maven2/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - http://developer.huawei.com/repo/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - https://storage.flutter-io.cn/download.flutter.io/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>      Required by:
>          project :app > project :flutter_sound
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> Exception: Gradle task assembleDebug failed with exit code 1
> ```



> When I add bellow native dependencies ,I got the error.(Meanwhile I add flutter `flutter_sound: ^8.4.2` in pubspec.yaml)
> 
> ```
> dependencies {
>     implementation 'com.huawei.hms:push:4.0.2.300'
> }
> apply plugin: 'com.huawei.agconnect'
> ```
> 
> Error Log
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:mergeDebugAssets'.
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
>    > Could not find com.github.canardoux:flutter_sound_core:8.4.2.
>      Searched in the following locations:
>        - http://maven.rongcloud.cn/repository/maven-releases/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - https://dl.google.com/dl/android/maven2/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - https://repo.maven.apache.org/maven2/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - http://developer.huawei.com/repo/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>        - https://storage.flutter-io.cn/download.flutter.io/com/github/canardoux/flutter_sound_core/8.4.2/flutter_sound_core-8.4.2.pom
>      Required by:
>          project :app > project :flutter_sound
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> Exception: Gradle task assembleDebug failed with exit code 1
> ```

Android项目的仓库地址还要引入
maven { url 'https://jitpack.io' }
这个项目内部引入的这个地址，主项目还要再引入一下
