### ISSUE TITLE
[BUG]: App size increased from 20Mb to 80Mb after adding this plugin

### ISSUE THREAD

**Issue by irajeshh** [Canardoux/flutter_sound#811]
## Flutter Sound Version : ^8.4.2

**FULL**

## Severity

- Result is not what expected ?

--------------------------------------------------------

## Platforms you faced the error 
- Android
- Real device

------------------------------------------------

**Describe the bug**
I was debugging, no errors. But when I released it, the size became tooo high.
My pupose is, just playing a 1sec mp3 file only.

# Logs!!!!
![image](https://user-images.githubusercontent.com/85046336/146942901-078ea986-76f5-461e-8359-c3bf8d37e5e3.png)

**Comment by alexda12** [comment]
If you want to play a small 1 sec MP3 , either go for the lite version or use another sound library that will be more suitable to your use-case. SoundPool, Asset Audio Player, Just Audio would suffice as they will not package up unneeded codecs.

**Comment by irajeshh** [comment]
@alexda12  will try and update
