### ISSUE TITLE
[ENH]: Suppress Logs

### ISSUE THREAD

**Issue by quickratio** [Canardoux/flutter_sound#827]
Firstly thank you for your great work, it's greatly appreciated;

**Is your feature request related to a problem? Please describe.**
Feature: would you consider adding in an option for non-verbose logs, they considerably decrease readability and make it extremely difficult to debug, i tried to see if there was an option but i could not find one.

**Describe the solution you'd like**
probably a simple argument in your functions like "suppressLogs: true".

Also, i managed to hook your streaming example into google speech to return speech to text, let me know if you'd like me to share it so you could use as a demo.

**Comment by Larpoux** [comment]
Hi @quickratio ,

I agree, all those logs are painful when we are not specifically debugging Flutter Sound code.
It is very easy to suppress those logs.
When you create your player or recorder do : 
```dart
FlutterSoundPlayer myPlayer = FlutterSoundPlayer(logLevel: Level.error);
FlutterSoundRecorder myRecorder = FlutterSoundRecorder(logLevel: Level.error);
```
or even : 
```dart
FlutterSoundPlayer myPlayer = FlutterSoundPlayer(logLevel: Level.nothing);
FlutterSoundRecorder myRecorder = FlutterSoundRecorder(logLevel: Level.nothing);
```
Eventually, if you need to change the loglevel dynamically during your run : 
```dart
myPlayer.setLogLevel(Level.error);
myRecorder.setLogLevel(Level.error);
```

If later you need to do a PR (Problem Report) into this github project, do no forget to restore a verbose level and post your logs. We definitely need logs when we try to work on an issue.

**Comment by quickratio** [comment]
Hi Larpoux,

Thanks for your quick response and info, i will do that.

**Comment by blablabla123-cell** [comment]
Can't change a log level now
![image](https://user-images.githubusercontent.com/74730689/224292012-a901fc63-1b13-4ac2-a8c8-91a3b280125d.png)
