### ISSUE TITLE
[ENH]: Solve the problem of the setAudioFocus method

### ISSUE THREAD

**Issue by MohsenHaydari** [Canardoux/flutter_sound#829]
Note: if you feel ready to improve τ, 
perhaps you could do a Pull Request ? This would be great !

------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

hi, thanks for this package.
setAudioFocus and openAudioSesshion do not work with AudioManager settings, and another problem that the program has when calling the openAudioSesshion method is that
The program changes the sound mode in the system, if necessary, this can only be done with the setAudioFocus method.
thanks

**Comment by Larpoux** [comment]
Hi @MohsenHaydari ,

The Audio Sessions Management inside Flutter Sound was a problem with compatibility with other libraries.
[see #825](https://github.com/Canardoux/flutter_sound/issues/825).

We are going to remove this code from Flutter Sound 9.0.
This will be released in a few days. Perhaps tomorrow.

**Comment by MohsenHaydari** [comment]
Thanks for the new update
