### ISSUE TITLE
[HELP]: flutterSoundHelper.duration in 9.*

### ISSUE THREAD

**Issue by marcoberetta96** [Canardoux/flutter_sound#832]
In `flutter_sound 8.*` I was using `FlutterSound.flutterSoundHelper.duration(audioPath)` to get the duration of an audio file.

How to do this in `flutter_sound 9.*`?

**Comment by Larpoux** [comment]
Duration was just a call to a Flutter FFmpeg verb.
The price to be able to do that was high. Too high.
If you really need to call this verb, you just have to depend on Flutter FFmpeg yourself, and call it.
This should not be very complicate.

**Comment by marcoberetta96** [comment]
Got it, thank you!
