### ISSUE TITLE
MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_player)[BUG]:

### ISSUE THREAD

**Issue by binemmanuel** [Canardoux/flutter_sound#834]
I get this exception though it looks like everything works fine on debug mode but the app crashes on none debug mode.

```
E/flutter ( 5779): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_player)
E/flutter ( 5779): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
E/flutter ( 5779): <asynchronous suspension>
E/flutter ( 5779): #1      FlutterSoundPlayer._openAudioSession
package:flutter_sound_lite/public/flutter_sound_player.dart:688
E/flutter ( 5779): <asynchronous suspension>
E/flutter ( 5779): #2      FlutterSoundPlayer.openAudioSession.<anonymous closure>
package:flutter_sound_lite/public/flutter_sound_player.dart:651
E/flutter ( 5779): <asynchronous suspension>
E/flutter ( 5779): #3      BasicLock.synchronized
package:synchronized/src/basic_lock.dart:33
```

**Comment by Larpoux** [comment]
Too many problems with 'resetPlugin'.
Someone should remove this bad hack, and do something better to solve the hot-reload crashes.
I am really not happy with this dirty hack. Better to do nothing than creating other problems

**Comment by Larpoux** [comment]
Here some informations on 'resetPlugin' for contributors wanting to clean things.

The problem occurs when we do a hot-reload : the dart appli is reinitialized but the native code does not know that there is a re-initialization. Then there is inconsistent between the forground in dart and the background in objective c or java. 
We get then a crash because the variable 'slotNo' is incorrect. 

Good luck to contributors wanting to work on this issue. Of course I can help

**Comment by bcaspe** [comment]
I'm getting this bug now as well. I can't find where resetPlugin is actually implemented in android (I see it in the ios version). If this is related to hot restarting, isn't it possible to simply add a check to kDebugMode? 
from line 518 in flutter_sound_player.dart:
`if (_reStarted && kDebugMode) {
      // Perhaps a Hot Restart ?  We must reset the plugin
      _logger.d('Resetting flutter_sound Player Plugin');
      _reStarted = false;
      await FlutterSoundPlayerPlatform.instance.resetPlugin(this);
    }`
I tried to do a fork but was not sure how to add my own fork to my pubspec.yaml...

**Comment by androidjayOK** [comment]
「message」: MissingPluginException(No implementation found for method resetPlugin on channel xyz.canardoux.flutter_sound_player) 
                                                                                                     「stack」:
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:522)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      AudioSoundListPlayer.initPlayer (package:huxue_module/base/player/audio_sound_player.dart:32)
                                                                                                    <asynchronous suspension>

**Comment by androidjayOK** [comment]
already use 9.4.11   exist qustion again

**Comment by Larpoux** [comment]
This issue is closed. Please open a new issue
