### ISSUE TITLE
[BUG]: Unhandled Exception when running getProgress();

### ISSUE THREAD

**Issue by pavittarsingh315** [Canardoux/flutter_sound#835]
## Flutter Sound Version : 9.1.1

- **FULL** flavor

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```:
```
|-- flutter_sound 9.1.1
|   |-- flutter_sound_platform_interface 9.1.1
|   |-- flutter_sound_web 9.1.1
|   |   |-- flutter_sound_platform_interface...
```

----------------------------------------------------------

## Severity

- Crash: No. Only an exception.

- Result is not what expected: Yes.

- Cannot build my App: No.

- Minor issue: I think so.

--------------------------------------------------------

## Platforms you faced the error 

- iOS: Simulator

- Android: Haven't tested.

- Flutter Web: Haven't tested.

- Emulator: Haven't tested.

- Real device: Haven't tested.

------------------------------------------------

**Describe the bug**
When attempting to get the duration of an audio file using the code below, a type cast exception is thrown.

**To Reproduce**
```
...
FlutterSoundPlayer? _audioPlayer = FlutterSoundPlayer();
await _audioPlayer!.openPlayer();
...
await _audioPlayer!.startPlayer(
  fromURI: this._audioUri,
  whenFinished: () async {
    await _audioPlayer!.stopPlayer();
  },
);
Duration? duration = (await _audioPlayer!.getProgress())["duration"];
print(duration);
...
```
This also reproduces the bug:
```
...
print(await _audioPlayer!.getProgress());
...
```
----------------------------------------------
# Logs:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
#0      MethodChannelFlutterSoundPlayer.getProgress
package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:211
<asynchronous suspension>

```
-----------------------------------------------------------------

**Comment by Larpoux** [comment]
@pavittarsingh315 : Sorry for the bug.
I am going to fix that today

**Comment by Larpoux** [comment]
@pavittarsingh315 : 

Flutter Sound 9.1.2 is released. I fixed your bug.
Feel free to re-open this issue if you have still problems.
