### ISSUE TITLE
[BUG]: Web recording files cannot be played normally.

### ISSUE THREAD

**Issue by zhourengui** [Canardoux/flutter_sound#839]
## Flutter Sound Version : 

- v9.0.0+

----------------------------------------------------------

## Severity

- Result is not what expected
--------------------------------------------------------

## Platforms you faced the error 

- iOS

- Android 

------------------------------------------------

**Describe the bug**
Web recording files cannot be played.
example file: https://github.com/rengui-hs/static_server/blob/main/0f82d71f-c717-4636-8266-e46ede1294be.mp3?raw=true.
This file can be played normally in the web.

https://user-images.githubusercontent.com/44863878/153206301-b16949df-9a2f-4803-8c6d-8c6100576814.mov

----------------------------------------------

# Logs!!!!

The logs look normal.
-----------------------------------------------------------------

**Comment by Larpoux** [comment]
We don't understand what you are trying to do.
If you need help you must be more explicit.

Note : there's no MP3 encoder available on Flutter Sound

**Comment by zhourengui** [comment]
> 我们不明白你想做什么。 如果你需要帮助，你必须更加明确。
> 
> 注意：Flutter Sound 上没有可用的 MP3 编码器

It is that the mp3 file above cannot be played normally on ios and android. The file source is the recording of the web.
