### ISSUE TITLE
listener on recorder progress is not working.

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [Canardoux/flutter_sound#840]
I am using flutter_sound in my project. Everything is working right but the listener on progress of recorder is not working.
Nothing happens when it is called.
Following is method used for recording and listening the progress.

```
void record() {
    mRecorder!
        .startRecorder(
      toFile: mPath,
      codec: codec,
      // audioSource: theSource,
    )
        .then((value) {
      recorderSubscription = mRecorder!.onProgress!.listen((e) {
        log("listenr is set on recorder");
        var date = DateTime.fromMillisecondsSinceEpoch(
            e.duration.inMilliseconds,
            isUtc: true);
        var txt = DateFormat('mm:ss:SS', 'en_GB').format(date);

        log("e = ${e.duration.inSeconds.toString()}");

        setState(() {
          recorderTxt = txt.substring(0, 8);
        });
      });
      setState(() {
        isRecording = true;
        isShowMsgField = false;
      });
      // controller.setIsRecording(isRecording.obs);
      showToast("Recording start");
    });
  }

```

**Comment by GeorgeAmgad** [comment]
Make sure you call `setSubscriptionDuration()` with a non-zero value before calling `onProgress.listen()`. 
By the way, this sets the interval of refreshing the onProgress stream (not the duration of the subscription) to let you balance between smoothness/percission and overall performance.

**Comment by UmairSaqibBhutta** [comment]
Thanks the problem is resolved, Actually I mistakenly removed the line of `setSubscriptionDuration()` .
