### ISSUE TITLE
[BUG]:Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [Canardoux/flutter_sound#858]
Flutter Sound Version : 9.1.3 or 9.1.6
ios
error log:
Undefined symbols for architecture arm64:
  "___gxx_personality_v0", referenced from:
      +[FlutterSound registerWithRegistrar:] in flutter_sound(FlutterSound.o)
      -[FlutterSoundPlayer startPlayerCompleted:duration:] in flutter_sound(FlutterSoundPlayer.o)
      -[FlutterSoundPlayer needSomeFood:] in flutter_sound(FlutterSoundPlayer.o)
      -[FlutterSoundPlayer updateProgressPosition:duration:] in flutter_sound(FlutterSoundPlayer.o)
      -[FlutterSoundPlayer audioPlayerDidFinishPlaying:] in flutter_sound(FlutterSoundPlayer.o)
      -[FlutterSoundPlayer pause] in flutter_sound(FlutterSoundPlayer.o)
      -[FlutterSoundPlayer resume] in flutter_sound(FlutterSoundPlayer.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Larpoux** [comment]
I had myself the same issue than you, yesterday.
I will work on that this afternoon.

Real iPhone or emulator?
Macintosh with Apple Silicon or x86?

**Comment by Larpoux** [comment]
@AndroidJohnsonWang 

I solved this issue with adding 2 flags in XCode > Build Settings > Other Linker Flags : 
```
-lc++
-lstd++
```

I lost two hours with this stupidity. Probably you lost also two hours. And probably other developers will lost also time.
Someone should add something in the Flutter Sound documentation.

**Comment by Larpoux** [comment]
@AndroidJohnsonWang ,

I added a few lines under the Trouble Shooting section of [the install doc](https://flutter-sound.canardoux.xyz/flutter_sound_install.html).

This is not perfect but better than nothing.
Note : if someone wants to work on the documentation, there is much work to do.
Feel free to update the doc and do a Pull Request.

**Comment by Adherentman** [comment]
add 2 flags then get this error 
ld: library not found for -lstd++

**Comment by Larpoux** [comment]
Yes, I got the same error myself a few days ago.
You can try to add only -lc++, and not -lstd++.
I think it is ok with just -lc++

**Comment by Adherentman** [comment]
add only -lc++ it's work! Thanks

**Comment by good-good-study** [comment]
I con't find this folder "Just add those 2 flags in XCode > Build Settings > Other Linker Flags :"

**Comment by good-good-study** [comment]
this  one ?
<img width="1052" alt="截屏2022-05-28 19 27 08" src="https://user-images.githubusercontent.com/20188392/170823477-5090971f-b884-4aef-af9a-a803982d93ee.png">

**Comment by mentholor** [comment]
> 这个 ？然后，它也有同样的错误！
> 
> <img alt="截屏2022-05-28 19 41 59" width="1199" src="https://user-images.githubusercontent.com/20188392/170824025-a936136a-85db-4c02-ba2e-b09dc2b427d7.png">

请问解决了吗

**Comment by mentholor** [comment]
> 这个 ？然后，它也有同样的错误！
> 
> <img alt="截屏2022-05-28 19 41 59" width="1199" src="https://user-images.githubusercontent.com/20188392/170824025-a936136a-85db-4c02-ba2e-b09dc2b427d7.png">

@good-good-study  请问解决了吗

**Comment by datdefboi** [comment]
Still getting the same error with -lc++ @Larpoux
