### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by ggss2020** [Canardoux/flutter_sound#859]

**Comment by ggss2020** [comment]
n/a

**Comment by Larpoux** [comment]
### Troubles shooting

#### Problem with Cocoapods

If you get this message \(specially after the release of a new Flutter Version\) :

```text
Cocoapods could not find compatible versions for pod ...
```

you can try the following instructions sequence \(and ignore if some commands gives errors\) :

```bash
cd ios
pod cache clean --all
rm Podfile.lock
rm -rf .symlinks/
cd ..
flutter clean
flutter pub get
cd ios
pod update
pod repo update
pod install --repo-update
pod update
pod install
cd ..
```

**Comment by Mocaris** [comment]
> 

is not work when i try it

**Comment by Mocaris** [comment]
> ### Troubles shooting
> #### Problem with Cocoapods
> If you get this message (specially after the release of a new Flutter Version) :
> 
> ```
> Cocoapods could not find compatible versions for pod ...
> ```
> 
> you can try the following instructions sequence (and ignore if some commands gives errors) :
> 
> ```shell
> cd ios
> pod cache clean --all
> rm Podfile.lock
> rm -rf .symlinks/
> cd ..
> flutter clean
> flutter pub get
> cd ios
> pod update
> pod repo update
> pod install --repo-update
> pod update
> pod install
> cd ..
> ```

is not work when i try it

**Comment by Mocaris** [comment]
> ### Troubles shooting
> #### Problem with Cocoapods
> If you get this message (specially after the release of a new Flutter Version) :
> 
> ```
> Cocoapods could not find compatible versions for pod ...
> ```
> 
> you can try the following instructions sequence (and ignore if some commands gives errors) :
> 
> ```shell
> cd ios
> pod cache clean --all
> rm Podfile.lock
> rm -rf .symlinks/
> cd ..
> flutter clean
> flutter pub get
> cd ios
> pod update
> pod repo update
> pod install --repo-update
> pod update
> pod install
> cd ..
> ```

I rollback it to 9.1.5 ,it can work
