### ISSUE TITLE
[HELP]: how is pcm16 represented as 8 bit integers?

### ISSUE THREAD

**Issue by goldentoaste** [Canardoux/flutter_sound#860]
------------

I need Help for :

- Using the API ?
-------------------------------------
## Here is my question :
So I am just confused with how the api captures the 16 bit pcm data but outputs a 8 bit integer array? I am making an app that needs to visualize audio by graphing it, and so far graphing each 8 bit integer don't make sense. Anything explaination would be helpful.

Here is the 8 bit integers plotted, for a 30hz sine wave.
![image](https://user-images.githubusercontent.com/59712548/158085293-c2e09754-a363-4b52-bac6-4a74fdad8442.png)

**Comment by Larpoux** [comment]
The management of Audio streams is very useful but is not perfect.
Actually I am busy working on a Flutter Sound successor. Its name is Taudio.
The API will conform to the [W3C recommandation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API).
This API is terrific, and it will be easy to get the audio data to draw a histogram.

Unfortunately, I am a little bit slow in the development, and the version 1.00 of Taudio will not be before several months.
If this delay is OK for you, I suggest that you wait for the v1.0 of Taudio.

In the meantime, you can look and play with [Flutter Web Audio API](https://api.dart.dev/stable/2.15.1/dart-web_audio/dart-web_audio-library.html) implementation on the web. 
Taudio API will be very similar to this library.

**Comment by Larpoux** [comment]
Live example : https://webaudioapi.com/samples/visualizer/

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode
https://www.oreilly.com/library/view/web-audio-api/9781449332679/ch05.html

**Comment by Larpoux** [comment]
[Live example](https://webaudioapi.com/samples/visualizer/)

**Comment by Larpoux** [comment]
Flutter Sound Streams are byte arrays.
For each INT16 value, you will get two bytes with a Little Endian format.

Taudio Streams will be streams of FLOAT32 arrays. Each sample will be a float between -1.0 and +1.0.
This is conformant with the W3C recommandation

**Comment by goldentoaste** [comment]
Yeah I see, the data needs to be converted with .asInt16List();
I think the current documentation could be a bit more clear with this.

**Comment by Larpoux** [comment]
@goldentoaste
Oh yes. The doc could be much better! 
@quickratio is able to retrieve the audio data from a byte stream.
Perhaps he/she can share with you how he/she did that.
