### ISSUE TITLE
[BUG]: using on web, and flutter_sound_recorder.js is still using old version in Flutter project

### ISSUE THREAD

**Issue by blawse** [Canardoux/flutter_sound#862]
## Flutter Sound Version : 

v 9.1.7

----------------------------------------------------------

## Severity

- App does not function without the volume being sent in the last parameter.

--------------------------------------------------------

## Platforms you faced the error 

- Flutter Web

------------------------------------------------

**Describe the bug**

using   flutter_sound: ^9.1.7 in pubspec.yaml, and yet the "flutter_sound_recorder.js" file that gets included is still the one that does not have the CB_updateRecorderProgress code fixed. i.e. it is still coming in as:

`me.callbackTable[CB_updateRecorderProgress](me.callback, me.deltaTime + distance, 0);
`

even though I can see if is fixed in the repo.

**To Reproduce**
Include the flutter_sound library on a flutter web app, and do anything that needs the volume. The parameter is hardcoded to 0.
----------------------------------------------

# Logs!!!!

No log needed... the code is correct in "flutter_sound_recorder.js" in the repo, but when flutter pub get is installing the library, the wrong .js file is coming down.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Fixed in Flutter Sound 9.4.7. Thanks to @bloemy7
