### ISSUE TITLE
[BUG]:PlatformException (PlatformException(Audio Player, startPlayer failure, null, null))

### ISSUE THREAD

**Issue by alperenbaskaya58** [Canardoux/flutter_sound#874]
## Flutter Sound Version : 9.1.9

- **FULL** or **LITE** flavor ? Full

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

## Severity

- Crash ? no

- Result is not what expected ?yes

- Cannot build my App ? no

- Minor issue ? no

--------------------------------------------------------

## Platforms you faced the error 

- iOS ? yes iphone 8 plus ios 14

- Android ? no

- Flutter Web ?idk

- Emulator ? no

- Real device ? yes

------------------------------------------------

**Describe the bug**
Recorded audio doesnt play on real ios device with path /var/mobile/Containers/Data/Application/8E613239-E966-4244-B5AD-832263CBB5E6/Library/Caches/12345.aac

**To Reproduce**
----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug).
To activate the logs, you must instantiate your modules with the Log Level set to `Level.debug` :
```
FlutterSoundPlayer myPlayer = FlutterSoundPlayer(logLevel: Level.debug);
FlutterSoundRecorder myRecorder = FlutterSoundRecorder(logLevel: Level.debug);
```
See [this](https://tau.canardoux.xyz/logger.html)

-----------------------------------------------------------------

flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 IOS:--> stopTimer
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundPlayer.log
package:flutter_sound/public/flutter_sound_player.dart:358
flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler
package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 IOS:<-- stopTimer
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundPlayer.log
package:flutter_sound/public/flutter_sound_player.dart:358
flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler
package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 IOS:<-- startPlayer
**_PlatformException (PlatformException(Audio Player, startPlayer failure, null, null))_**

**Comment by xuechen628** [comment]
same problem here with version 9.2.2, any workaround? Thanks!

**Comment by Larpoux** [comment]
I don't think that  "/var/mobile/Containers/Data/Application/8E613239-E966-4244-B5AD-832263CBB5E6/Library/Caches/12345.aac" is a correct path on a real device.

How do you do to get this path?

**Comment by xuechen628** [comment]
Thanks for reply! The problem happens also on real device. I think it's codec problem, this problem happens if I play audio file that used AAC MP4 codec, but if use such as Opus CAF then doesn't have this problem at all.

**Comment by Larpoux** [comment]
I don't see why this issue.
Perhaps there is a conflict between AAC/ADTS and AAC/MP4.
If you are sure that your record is MP4, then you can try to use a "xxx.mp4" file extension.
But I am not sure at all that it will fix the problem.

**Comment by Larpoux** [comment]
Is it possible that you post your record so that I will probe it with FFmpeg or other utilities app?

**Comment by xuechen628** [comment]
Hi, I fond my problem now, after recording I copy the audio file form cache folder to other folder, it can be played without problem. but after app restarted, the copied file in other folder is lost. then have the problem "PlatformException(Audio Player, startPlayer failure, null, null)". 
Thanks a lot for reply and your time!!!

**Comment by Larpoux** [comment]
👍

**Comment by zhou-candy** [comment]
Hello, I have the same problem, the recording file can also be known, but it cannot be played.Click Play and an error occurs：PlatformException (PlatformException(Audio Player, startPlayer failure, null, null))

**Comment by zhou-candy** [comment]
我知道怎么解决了，需要初始化AudioSession。

**Comment by isiyemijoe** [comment]
For those who still have this issue, all you need to do is initialise the audio session before using this plugin like this 

  setupSession() async {
    final ses = await session;
    await ses.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      avAudioSessionCategoryOptions:
          AVAudioSessionCategoryOptions.allowBluetooth | AVAudioSessionCategoryOptions.defaultToSpeaker,
      avAudioSessionMode: AVAudioSessionMode.spokenAudio,
      avAudioSessionRouteSharingPolicy: AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.voiceCommunication,
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
      androidWillPauseWhenDucked: true,
    ));
  }

  final session = AudioSession.instance;


Make sure you call setupSession() before recording;

**Comment by loolooii** [comment]
@isiyemijoe this solved my recording problem, but still having trouble playing the file.

**Comment by Larpoux** [comment]
@loolooii if this solve your recording problem, probably good if you enter a new issu for your player problem
