### ISSUE TITLE
[HELP]: How to record .mp3 file.

### ISSUE THREAD

**Issue by good-good-study** [Canardoux/flutter_sound#898]
How to record .mp3 file ？

**Comment by good-good-study** [comment]
toStream can only be used with codec == Codec.pcm16

What other audio formats are supported toStream？

**Comment by shobith10** [comment]
which version of flutter sound is more compatible

**Comment by Larpoux** [comment]
> await recorder.startRecorder(
    toFile: 'audio', codec: audio.Codec.defaultCodec);

You can try something like:
'''
Sring path = '$tempdir/audio' ;
startRecorder(toFile: '$path.wav', codec: Codec. pcmWav) ;
...
FFmpegKit.execute('-i $path.wav $path.mp3').then((
...
'''

**Comment by shobith10** [comment]
i tried startRecoding it records correctly, but path returned on stropRecorder is empty or says no such file directory

 final path = await recorder.stopRecorder();

**Comment by shobith10** [comment]
this method worked for me , its better to use aac format than mp3, it supports almost all kinds browsers    
.....
Directory tempDir = await getApplicationDocumentsDirectory();
    String path = tempDir.path + '/audio.aac';

    print("directory path: $path");

    //audioFile = await File('${tempDir.path}/audio.mp3');
    await recorder.startRecorder(toFile: path, codec: audio.Codec.aacMP4);
  }

**Comment by zhouxin1233** [comment]
> > await recorder.startRecorder(
> > toFile: 'audio', codec: audio.Codec.defaultCodec);
> 
> You can try something like: ''' String path = '$tempdir/audio' ; startRecorder(toFile: '$path.wav', codec: Codec. pcmWav) ; ... FFmpegKit.execute('-i $path.wav $path.mp3').then(( ... '''

it‘s not work，

`    var ffmpegSession = await FFmpegKit.execute('-i $sourcePath $convertResultPath.mp3');`

Automatic encoder selection failed for output stream #0:0. Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.
E/log  FlutterLog  convertAudio (27327): Error selecting an encoder for stream 0:0
