### ISSUE TITLE
[HELP]:

### ISSUE THREAD

**Issue by shobith10** [Canardoux/flutter_sound#899]
## For example the _Element_ τ room ?

------------

I need Help for :

- Using the API ?

- Generate an iOS or Android App ?

- Debugging my App ?

- Other ?

-------------------------------------
## Here is my question :
It was said that in a previous closed issue, codec does not support mp3, you need to record audio in a supported codec and convert file to MP3 , so how to convert a file to MP3

**Comment by Larpoux** [comment]
- record a WAVE file
- convert the WAVE file to MP3 with just a simple call to the FFmpeg Kit plugin API
