### ISSUE TITLE
[BUG]: ___gxx_personality_v0 already added flags -lstdc++ -lc++

### ISSUE THREAD

**Issue by wuyuancai** [Canardoux/flutter_sound#907]
Undefined symbols for architecture x86_64:
      "___gxx_personality_v0", referenced from:
          +[FlutterSound registerWithRegistrar:] in flutter_sound(FlutterSound.o)
          -[FlutterSoundPlayer startPlayerCompleted:duration:] in flutter_sound(FlutterSoundPlayer.o)
          -[FlutterSoundPlayer needSomeFood:] in flutter_sound(FlutterSoundPlayer.o)
          -[FlutterSoundPlayer updateProgressPosition:duration:] in flutter_sound(FlutterSoundPlayer.o)
          -[FlutterSoundPlayer audioPlayerDidFinishPlaying:] in flutter_sound(FlutterSoundPlayer.o)
          -[FlutterSoundPlayer pause] in flutter_sound(FlutterSoundPlayer.o)
          -[FlutterSoundPlayer resume] in flutter_sound(FlutterSoundPlayer.o)
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="871" alt="image" src="https://user-images.githubusercontent.com/19992054/174041684-116ff740-4359-4949-8160-c1c22230b3c0.png">

Library not found for -lstd++, so i want use -lstdc++, but use -lstdc++ is error

**Comment by disconzi01** [comment]
@wuyuancai how did you solve this?

**Comment by wuyuancai** [comment]
Global config, not only flutter_sound** config
