### ISSUE TITLE
[HELP]: `flutter_sound_lite` It's been a long time since I updated it, Can you update it

### ISSUE THREAD

**Issue by git-boya** [Canardoux/flutter_sound#910]
i have a problem #880 , It has been resolved on the `flutter_sound`, but `lite` not upgrade.

thanks!

**Comment by liemfs** [comment]
According to this
https://flutter-sound.canardoux.xyz/guides_lite-full.html

flutter_sound has no Full / Lite flavor anymore
Now its just single flavor only
You should move to flutter_sound, and abandoned flutter_sound_lite
