### ISSUE TITLE
[HELP]: How to get file duration without calling .startPlayer and listening to onProgress

### ISSUE THREAD

**Issue by superflyer11** [Canardoux/flutter_sound#922]
How to get file duration without calling .startPlayer and listening to onProgress

**Comment by muneebahmad0600** [comment]
any updated?

**Comment by Larpoux** [comment]
Flutter Sound is a plug-in to record and play sound.
It is not for handling sound files.
Maybe you could look to [ffmpeg](https://pub.dev/packages/ffmpeg_kit_flutter) which is a great library for handling files.
