### ISSUE TITLE
[ENH] Solution for Exception of Reply already submitted!

### ISSUE THREAD

**Issue by netsesame2** [Canardoux/flutter_sound#938]
> Question to resolve
```
flutter_sound: 9.2.13
platform: Android (not tested in iOS, maybe the same) 
Issue: When hot restart, openPlayer and openRecorder method will throw "Reply already submitted" Exception.
```

> Reason to analysis
```
/// flutter_sound_player.dart
if (_reStarted) {
      // Perhaps a Hot Restart ?  We must reset the plugin
      _logger.d('Resetting flutter_sound Player Plugin');
      _reStarted = false;
      await FlutterSoundPlayerPlatform.instance.resetPlugin(this);
}
```
```
/// FlutterSoundManager.java
public void resetPlugin( final MethodCall call, final Result result )
{
    for (int i = 0; i < slots.size () ; ++i)
    {
	    if (slots.get ( i ) != null)
	    {
		    slots.get ( i ).reset(call, result);
	    }
	    slots   = new ArrayList<FlutterSoundSession>();
    }
    result.success(0);
}
```
slots is a list to hold FlutterSoundPlayer and FlutterSoundRecorder objects, which both has a reset method:
```
// FlutterSoundPlayer.java
// FlutterSoundRecorder.java
void reset(final MethodCall call, final MethodChannel.Result result)
{
    m_flautoPlayer.closePlayer();
    result.success ( getPlayerState() );
}
```
In above code, result.success() method is invoked for each object in slots, and invoked again in the end of  resetPlugin()
Let's have a look at source of Result in flutter:
```
private static class Reply implements BinaryMessenger.BinaryReply {
  @NonNull private final FlutterJNI flutterJNI;
  private final int replyId;
  // 1 
  private final AtomicBoolean done = new AtomicBoolean(false);
  Reply(@NonNull FlutterJNI flutterJNI, int replyId) {
    this.flutterJNI = flutterJNI;
    this.replyId = replyId;
  }
  @Override
  public void reply(@Nullable ByteBuffer reply) {
    // 2
    if (done.getAndSet(true)) {
      throw new IllegalStateException("Reply already submitted");
    }
    if (reply == null) {
      flutterJNI.invokePlatformMessageEmptyResponseCallback(replyId);
    } else {
      flutterJNI.invokePlatformMessageResponseCallback(replyId, reply, reply.position());
    }
  }
}
```
That is, the field done for each single instance of Result, can be assigned to true for only once.
So, multiple invokes of Result.success will throw "Reply already submitted" exception.
Knowing the reason, the solution will be very simple: 
```
// FlutterSoundPlayer.java
// FlutterSoundRecorder.java
void reset(final MethodCall call, final MethodChannel.Result result)
{
    m_flautoPlayer.closePlayer();
    /// result.success ( getPlayerState() ); // just comment it
}
```
In each reset method, comment or remove the result.success invoke line. 
In fact, for the purpose of resetPlugin, no sense to get each reset result, just return a single 0,  that is enough.
> Above solution works well, no exception is thrown after hot rebuild.

**Comment by JamesAllgood** [comment]
how do I apply this fix to my code? tried searching for the file flutter_sound_player.dart but can't see it anywhere. 

Flutter sound used to work fine in my code but has recently stopped working with this error coming up

**Comment by netsesame2** [comment]
@JamesAllgood There is no need to change any dart file. Only some java file need to be fixed

**Comment by MINEGHOST007** [comment]
fix this na and release a version

**Comment by Larpoux** [comment]
@MINEGHOST007 ,

The fix proposed by @netsesame2 seems interesting and well documented.
I don’t see any reason not to merge it in flutter sound.
I am going to release a new version soon. Maybe tomorrow.

**Comment by Larpoux** [comment]
@netsesame2 , @MINEGHOST007 

Flutter Sound 9.4.11 is released. It incorporates this fix proposed by @netsesame2 .
Thank you @netsesame2 for your contribution

**Comment by MINEGHOST007** [comment]
Even if you add wave forms it would be great

**Comment by Larpoux** [comment]
@MINEGHOST007 : sorry, I don't understand your point.

**Comment by netsesame2** [comment]
Glad to see the fixes has finally be the official.
God bless Ukraine.
@Larpoux
