### ISSUE TITLE
Need an api to get the duration of remote audio file

### ISSUE THREAD

**Issue by venkateshqurhealth** [Canardoux/flutter_sound#939]
Note: if you feel ready to improve τ, 
perhaps you could do a Pull Request ? This would be great !

------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by muneebahmad0600** [comment]
Need help @Larpoux  @venkateshqurhealth  @matsu911  @ened  @MagicalTux
