### ISSUE TITLE
[HELP]: Is it possible with this lib to start a recording from background?

### ISSUE THREAD

**Issue by 701789262a** [Canardoux/flutter_sound#976]
When starting the recording when the app is open, it records successfully, when a recording is started from background state, it records the audio for the selected amount of time (I handled this with timer and delay) but the resulting audio is empty -- just silence.

I was wondering if this is a limitation imposed by android or a specific limitation from this library.

**Comment by sondresorbye** [comment]
+1

**Comment by sondresorbye** [comment]
Reopen
