### ISSUE TITLE
[BUG]:Calling startPlayer will Crash when there is no network available

### ISSUE THREAD

**Issue by lurongshuang** [Canardoux/flutter_sound#985]
## Flutter Sound Version : 

Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-arm64, locale
    zh-Hans-CN)
flutter_sound 9.2.13

----------------------------------------------------------

## Severity

Crash

--------------------------------------------------------

## Platforms you faced the error 
- Android 

------------------------------------------------

**Describe the bug**
 Calling startPlayer will flash back when there is no network available
----------------------------------------------

# Logs!!!!
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   new FlutterSoundPlayer (package:flutter_sound/public/flutter_sound_player.dart:132:13)
I/flutter (31928): │ #1   AudioRecorderService.onInit (package:wordflows/utils/audio_recorder_services/audio_recorder_services.dart:38:16)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 ctor: FlutterSoundPlayer()
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:511:13)
I/flutter (31928): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:17)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 FS:---> openAudioSession
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:524:15)
I/flutter (31928): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:17)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 Resetting flutter_sound Player Plugin
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[GETX] Instance "DragWordController" has been initialized
I/flutter (31928): [inf] 2023-08-21 14:27:48.162909 [fijk] FijkPlayer{id:2} invoke release #1 -> done
I/flutter (31928): ~~~ paused. hashcode:332042404, video:3753184016319280 controllerHashCode=248420070
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer.openPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:194:13)
I/flutter (31928): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:96:19)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 ---> openPlayerCompleted: true
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer.openPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:209:13)
I/flutter (31928): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:96:19)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 <--- openPlayerCompleted: true
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:542:13)
I/flutter (31928): │ #1   <asynchronous suspension>
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 FS:<--- openAudioSession
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:779:13)
I/flutter (31928): │ #1   FlutterSoundPlayer.startPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:759:17)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 FS:---> startPlayer 
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer._stop (package:flutter_sound/public/flutter_sound_player.dart:1099:13)
I/flutter (31928): │ #1   FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:806:11)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 FS:---> _stop 
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:296:13)
I/flutter (31928): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:113:19)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 ---> stopPlayerCompleted: true
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:311:13)
I/flutter (31928): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:113:19)
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 <--- stopPlayerCompleted: true
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (31928): │ #0   FlutterSoundPlayer._stop (package:flutter_sound/public/flutter_sound_player.dart:1126:13)
I/flutter (31928): │ #1   <asynchronous suspension>
I/flutter (31928): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (31928): │ 🐛 FS:<--- _stop 
I/flutter (31928): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
V/OppoMediaPlayer(31928): system load
V/OppoMediaPlayer(31928): new OppoMediaPlayer
I/OppoMediaPlayer(31928): new mediaplayer ,packageName = tech.qqss.wordflows
I/OppoMediaPlayer(31928): isPlaying() isOppoCreate=false
I/OppoMediaPlayer(31928): setDataSource(String) isOppoCreate=false
I/OppoMediaPlayer(31928): setDataSource(path, headers) isOppoCreate=false
V/MediaHTTPService(31928): MediaHTTPService(android.media.MediaHTTPService@8008ce8): Cookies: null
I/OppoMediaPlayer(31928): prepare() isOppoCreate=false
V/MediaHTTPService(31928): makeHTTPConnection: CookieManager created: java.net.CookieManager@69adf01
V/MediaHTTPService(31928): makeHTTPConnection(android.media.MediaHTTPService@8008ce8): cookieHandler: java.net.CookieManager@69adf01 Cookies: null
D/CrashReport( 2485): main stack:android.media.MediaPlayer._prepare(Native Method)
D/CrashReport( 2485): android.media.MediaPlayer.prepare(MediaPlayer.java:1442)
D/CrashReport( 2485): com.dooboolab.TauEngine.FlautoPlayerMedia._startPlayer(FlautoPlayerMedia.java:52)
D/CrashReport( 2485): com.dooboolab.TauEngine.FlautoPlayer.startPlayer(FlautoPlayer.java:203)
D/CrashReport( 2485): com.dooboolab.fluttersound.FlutterSoundPlayer.startPlayer(FlutterSoundPlayer.java:201)
D/CrashReport( 2485): com.dooboolab.fluttersound.FlutterSoundPlayerManager.onMethodCall(FlutterSoundPlayerManager.java:118)
D/CrashReport( 2485): io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
D/CrashReport( 2485): io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
D/CrashReport( 2485): io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
D/CrashReport( 2485): io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
D/CrashReport( 2485): android.os.Handler.handleCallback(Handler.java:883)
D/CrashReport( 2485): android.os.Handler.dispatchMessage(Handler.java:100)
D/CrashReport( 2485): android.os.Looper.loop(Looper.java:238)
D/CrashReport( 2485): android.app.ActivityThread.main(ActivityThread.java:7820)
D/CrashReport( 2485): java.lang.reflect.Method.invoke(Native Method)
D/CrashReport( 2485): com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
D/CrashReport( 2485): com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
D/CrashReport( 2485): 
D/CrashReport( 2485): short msg:Find process anr, but unable to get anr message.
D/CrashReport( 2485): long msg:null
D/CrashReport( 2485):  threads:18
I/CrashReport( 2485): found visible anr , start to upload!
D/CrashReport( 2485): trace file:/data/user/0/tech.qqss.wordflows/app_bugly/manual_bugly_trace_1692599436715.txt
D/CrashReport( 2485): trace file exists
I/CrashReport( 2485): trace file rename :true
D/CrashReport( 2485): save main stack trace
I/CrashReport( 2485): ROM ID: Oppo/COLOROS/V7.1
D/CrashReport( 2485): isAppForeground:true
D/CrashReport( 2485): [Database] insert t_cr success.
D/CrashReport( 2485): insert t_cr success!
I/CrashReport( 2485): backup anr record success!

-----------------------------------------------------------------
E/CrashReport( 2485): # CRASH STACK: 
E/CrashReport( 2485): android.media.MediaPlayer._prepare(Native Method)
E/CrashReport( 2485): android.media.MediaPlayer.prepare(MediaPlayer.java:1442)
E/CrashReport( 2485): com.dooboolab.TauEngine.FlautoPlayerMedia._startPlayer(FlautoPlayerMedia.java:52)
E/CrashReport( 2485): com.dooboolab.TauEngine.FlautoPlayer.startPlayer(FlautoPlayer.java:203)
E/CrashReport( 2485): com.dooboolab.fluttersound.FlutterSoundPlayer.startPlayer(FlutterSoundPlayer.java:201)
E/CrashReport( 2485): com.dooboolab.fluttersound.FlutterSoundPlayerManager.onMethodCall(FlutterSoundPlayerManager.java:118)
E/CrashReport( 2485): io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/CrashReport( 2485): io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/CrashReport( 2485): io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/CrashReport( 2485): io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/CrashReport( 2485): android.os.Handler.handleCallback(Handler.java:883)
E/CrashReport( 2485): android.os.Handler.dispatchMessage(Handler.java:100)
E/CrashReport( 2485): android.os.Looper.loop(Looper.java:238)
E/CrashReport( 2485): android.app.ActivityThread.main(ActivityThread.java:7820)
E/CrashReport( 2485): java.lang.reflect.Method.invoke(Native Method)
E/CrashReport( 2485): com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/CrashReport( 2485): com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E/CrashReport( 2485): #++++++++++++++++++++++++++++++++++++++++++#

**Comment by lurongshuang** [comment]
@Larpoux Asking for help

**Comment by mere-code** [comment]
解决了吗？

**Comment by xxzj990** [comment]
same error

**Comment by lurongshuang** [comment]
等待回复

**Comment by pilgrim1385** [comment]
same
