### ISSUE TITLE
[DOC] Como Puedo enviar lo grabado a una api rest via http para ser subido a una base de datos?

### ISSUE THREAD

**Issue by kvzon1984** [Canardoux/flutter_sound#989]
Note : if you want to improve the documention, it is great !
You may consider also using the _commento_ panel at the bottom of every pages.
Or writing a new page with the Wiki.
Or even doing a Pull Request.

--------

- Is the documentation wrong ?

- Is the documentation inaccurate ?

- Is the documentation missing for a specific object ?

- Other ?

**Comment by efraespada** [comment]
@kvzon1984 

First of all, you should write your question in English.

In its pure state, you can work with the bytes of any file (as base64 for example), but it is not a question for this repository. You can look for information on Google.

You can send the `Uint8List` data to your backend.
