### ISSUE TITLE
PlatformException(startRecorder, startRecorder, Failure to start recorder, null)

### ISSUE THREAD

**Issue by Pgrammerybj** [Canardoux/flutter_sound#990]
## For example the _Element_ τ room ?

------------

I need Help for :

在使用startRecorder的时候，发现FlutterSoundRecorderPlatform.instance.startRecorder()方法内部抛出了一个异常：Error:PlatformException(startRecorder, startRecorder, Failure to start recorder, null)

- Using the API ? flutter_sound: ^9.2.13

- Generate an iOS or Android App ? Android

- Debugging my App ? Yes

- Other ?

-------------------------------------

**Comment by sonnm2023** [comment]
I have a same bug. I check my audio record permission before start to record the audio. Then it works ok.
