### ISSUE TITLE
How to get duration of an audio file without playing

### ISSUE THREAD

**Issue by wzlsquall** [Canardoux/flutter_sound#994]
How to get duration of an audio file without playing

**Comment by zhouzhou94alone** [comment]
I also hope there is

**Comment by thanglq1** [comment]
I also hope there is. Hi @wzlsquall Is there any solution to get duration?

**Comment by muneebahmad0600** [comment]
Any update? @zhouzhou94alone  @thanglq1 @wzlsquall @matsu911  @ened

**Comment by Larpoux** [comment]
Flutter Sound is a plug-in to record and play sound.
It is not for handling sound files.
Maybe you could look to [ffmpeg](https://pub.dev/packages/ffmpeg_kit_flutter) which is a great library for handling files.
