### ISSUE TITLE
[HELP]:

### ISSUE THREAD

**Issue by Belmekhfisalim** [Canardoux/flutter_sound#996]
**Issue Description:**
I am encountering an issue with voip when recording audio in my Flutter app on iPhones. After activating voip for call reception outside the app, there is a problem with sending a voice message. The audio icon persists even after recording is completed.

**Steps to Reproduce:**
1. Enable voip for call reception outside the app.
2. Attempt to send a voice message.
3. Observe the persistence of the audio icon even after completing the recording.

**Context:**
- Flutter Version: 3.7.3
- Package Version (flutter_sound): 9.2.13
- Your System Version: macOS 13.6

**Relevant Code:**
[Provide relevant snippets of code related to the voip call reception and audio recording.]

**Expected Behavior:**
The audio icon should disappear after completing the recording, and the voip functionality for call reception outside the app should work seamlessly.

**Additional Notes:**
I have checked permissions and made sure that the voip setup is correct. The issue seems to be specific to iPhones. Any guidance on resolving this would be appreciated.

**Flutter Doctor**
[!] Flutter (Channel stable, 3.7.3, on macOS 13.6 22G120 darwin-x64, locale en-DZ)
    ! The flutter binary is not on your path. Consider adding /Users/belmekhfisalim/Downloads/flutter-2/bin to your path.
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart-sdk/2.18.5/libexec/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/belmekhfisalim/Downloads/flutter-2. Consider adding /Users/belmekhfisalim/Downloads/flutter-2/bin
      to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] HTTP Host Availability

![IMG_3492](https://github.com/Canardoux/flutter_sound/assets/66067738/535cf517-923a-4e11-995c-c40ddc901461)
![Screenshot 2023-11-26 at 10 00 37](https://github.com/Canardoux/flutter_sound/assets/66067738/76f26638-b5bd-42cb-8cb2-8082978b1167)

Thank you for your assistance!

**Comment by Larpoux** [comment]
This issue must be analyzed
